### ISSUE TITLE
Dec 2021 Updates

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#1004]
- [x] Substrate (polkadot-v0.9.11)
- [ ] Replace darwinia-header-mmr with pallet-mmr
- [x] Integrate BEEFY

<img width="1910" alt=" Dec 2021 Updates" src="https://user-images.githubusercontent.com/16152305/146887021-f63a22e4-d401-4aa1-9f81-9d95c9ab7f57.png">

**Comment by HackFisher** [comment]
Related #1055
