### ISSUE TITLE
Should Not Depend on Frame

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#1013]
```
evm/lib.rs
pub use dp_evm::{
	Account, CallInfo, CreateInfo, ExecutionInfo, LinearCostPrecompile, Log, Precompile,
	PrecompileSet, Vicinity,
};
```

It is not a good idea to access the primitives by depending on another frame.
We should depend on primitives (dp-evm) directly. That is why we extract them to a single primitives crate.

**Comment by HackFisher** [comment]
Not clear, currently it is depending on frontier directly which is third party, so I'm afraid we can not assume how they organize primitives.

**Comment by AurevoirXavier** [comment]
Should follow this guide. https://github.com/paritytech/substrate/blob/master/scripts/ci/gitlab/ensure-deps.sh
