### ISSUE TITLE
Research what migration should do when using note_stalled.

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#1017]
Grandpa could be stalled when there are not enough(> 2/3) validators participate finality.

In this case, there is a note_stalled extrinsic from grandpa to recover the network, but it means force changes of authorities set, and will probably affect s2s bridge.

**Comment by AsceticBear** [comment]
What is the priority of this issue?

**Comment by HackFisher** [comment]
> What is the priority of this issue?

Low priority, and I might find a simple solution to deal with this:

https://github.com/darwinia-network/parity-bridges-common/blob/7be2b478b49bc8e87ddfe034076e9e80e2f126f6/modules/grandpa/src/lib.rs#L191-L192

In this case, here we can try remove the `BestFinalized ` storage and call `initialize ` bridge again using owner account.

**Comment by AurevoirXavier** [comment]
I think the steps would be:
1. You need to wait for a new era. (New validator set lived)
2. `note_stalled` to change the old validator set with current's and make sure the finalization recovered.
3. Initializing the S2S bridge with the latest state.
