### ISSUE TITLE
Known DVM issues before the next public release

### ISSUE THREAD

**Issue by AsceticBear** [darwinia-network/darwinia-common#1082]
There are some issues that need to be fixed before the common library loading on the Crab network.

## Must

- [x] #1108 https://github.com/darwinia-network/darwinia-common/pull/1107
- [x] #1083 https://github.com/darwinia-network/darwinia-common/pull/1107

## Better 

- [ ] #1081
- [ ] #1084
- [ ] #1074

**Comment by AurevoirXavier** [comment]
How is the progress now?

**Comment by AsceticBear** [comment]
All must have issues have been fixed. Close it now.
