### ISSUE TITLE
Can not fetch the genesis block in Crab

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-common#1099]
```
curl -fsS https://darwinia-crab.api.onfinality.io/public/ -d '{"id":1,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x0",false]}' -H 'Content-Type: application/json'
{"jsonrpc":"2.0","result":null,"id":1}
```

**Comment by xiaoch05** [comment]
the genesis block is 4969901
you can't get block by number 0.

**Comment by AsceticBear** [comment]
@hujw77 As xiao cheng said above. Crab installed DVM's component at the height of 4969901. The substrate mapping sync workers establish block by parsing pre-digest in the substrate block header. Prior to this height, there was no pre-digest and no block.
