### ISSUE TITLE
Separate `StakingLock` from `StakingLedger`

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#121]

**Comment by AurevoirXavier** [comment]
`bond`(new ledger) will overwrite the locks after `force_unstake` or `unbond`(all stake).

**Comment by HackFisher** [comment]
Related https://github.com/darwinia-network/darwinia-common/issues/122

I tend to keep the currently struct and do the general reap stuff in a stand alone trait.

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia-common/pull/799/files#diff-847a61d013ce4aedef41be8e70a2b09d96eb3ac5d5ce3d3da45e03915ab1fa90 Could be optimized by this.
