### ISSUE TITLE
Add merkle patricia tree (MPT) precompile

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-common#1230]
## Goal
To make message verify process generalization:
1. Fetch light client's `state_root` of finalized header.
2. Use MPT precompile to verify the message/storage proof.

## Changes
1. Change BSC precompile to only fetch `state_root`. 
```solidity
interface IBSCLightClient{
    function state_root() external view returns (bytes32);
}
```
2. Add MPT precompile interface.
```solidity
interface IMerklePatriciaTrie {
    function verify_single_storage_proof(
        bytes32 root,
        address account,
        bytes[] calldata accountProof,
        bytes32 storageKey,
        bytes[] calldata storageProof
    ) external view returns (bytes memory value);

    function verify_multi_storage_proof(
        bytes32 root,
        address account,
        bytes[] calldata accountProof,
        bytes32[] calldata storageKeys,
        bytes[][] calldata storageProof
    ) external view returns (bytes[] memory values);
}
```

## More
After the change,  Eth2.0/BSC light client could even implement the MPT lib in solidity way.

**Comment by HackFisher** [comment]
This proposal is OK as a temporary solution for quicker support of eth2 mpt verify.

But later, I have plan that the bsc pallet and this precompile will be removed and replaced with same solidity implementation, in that case, the usage will be replaced using new solidity implementation.
