### ISSUE TITLE
Keep the precompile address the same in different network

### ISSUE THREAD

**Issue by AsceticBear** [darwinia-network/darwinia-common#1236]
We'd better follow this simple rule: For certain precompile, its smart contract chain address should be the same in different networks, either on mainnet or on testnet.

**Comment by wuminzhe** [comment]
It may be safer to start with a high number

**Comment by AsceticBear** [comment]
This had been discussed before, we have reserved enough address slots to keep compatible with Ethereum design.

**Comment by wuminzhe** [comment]
> This had been discussed before, we have reserved enough address slots to keep compatible with Ethereum design.

not only ethereum, but also other substrate-based evm chains.

**Comment by AsceticBear** [comment]
This has been done. Close it.
