### ISSUE TITLE
Transfer precompile refactor

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#1259]
Using ring.transfer for dispatch call.

**Comment by HackFisher** [comment]
Kton precompile require clean and refactor too.

**Comment by HackFisher** [comment]
Redesign kton precompile and make its ABI compatible with ERC20 standards.

Reference: Moonbeam's Erc20BalancesPrecompile etc


Kton withdraw can also use dispatch then.

**Comment by AsceticBear** [comment]
> Using ring. transfer for dispatch call.

```rs
[call]  // It'll be part of darwinia-ethereum pallet
pub fn ring_back(origin, dest_acccount_id, value) {
    let source_account_id = ensure_signed(origin);
    source_account_id.trnasfer(dest_acccount_id, value);
}

user -> dispatch_precompile(ring_back_call_encoded)
```

I write such a pseudocode example to confirm that I understand correctly. It seems doable.

**Comment by wuminzhe** [comment]
Which of `withdraw` or `transfer` should be used as the name of the api?

**Comment by HackFisher** [comment]
> Which of `withdraw` or `transfer` should be used as the name of the api?

`transfer_ring_to_substrate_account`
