### ISSUE TITLE
Review chain_id settings in ethereum transact, should follow EIP 155

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#1273]
https://github.com/darwinia-network/darwinia-common/blob/b31765ce4460bb65d23e2e3c4bc9b003157e7f1d/frame/dvm/ethereum/src/lib.rs#L1038

https://eips.ethereum.org/EIPS/eip-155

**Comment by AsceticBear** [comment]
I have thought that after https://github.com/darwinia-network/darwinia-common/issues/1239 is done, the internal transaction is useless anymore. But, solidity callback https://github.com/darwinia-network/darwinia-common/pull/1227 rely on the `internal _transact` again. I didn't find a better way to avoid this so far.

**Comment by HackFisher** [comment]
> I have thought that after #1239 is done, the internal transaction is useless anymore. But, solidity callback #1227 rely on the `internal _transact` again. I didn't find a better way to avoid this so far.

This part related internal transact could be removed, but other places require review and check too.

**Comment by AsceticBear** [comment]
This part meant ? in the solidity callback?

**Comment by HackFisher** [comment]
> This part meant ? in the solidity callback?

Internal transaction related codes: 

https://github.com/darwinia-network/darwinia-common/blob/b31765ce4460bb65d23e2e3c4bc9b003157e7f1d/frame/dvm/ethereum/src/lib.rs#L1038
