### ISSUE TITLE
Add `#![warn(missing_docs)]`?

### ISSUE THREAD

**Issue by AsceticBear** [darwinia-network/darwinia-common#1276]
Long-term, requiring additional documentation can be beneficial.

**Comment by AurevoirXavier** [comment]
We can start this on some our custom pallets.

**Comment by AsceticBear** [comment]
There is a related issue https://github.com/darwinia-network/darwinia-docs/pull/304. Prefer to enhance the code docs in our customed pallet first, especially for items `Const`, `Extrinsic`, and `Storage`, then sync the code notes to the `darwinia-docs` website.
