### ISSUE TITLE
Remove usable balance and fee market rpcs

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#1283]

**Comment by AurevoirXavier** [comment]
Fee market RPC was already removed.

**Comment by AurevoirXavier** [comment]
What about the `staking::power`?

**Comment by HackFisher** [comment]
> What about the `staking::power`?

Yes, but need to check the usage with SDK and apps developers. @JayJay1024 @cinlk

**Comment by JayJay1024** [comment]
> > What about the `staking::power`?
> 
> Yes, but need to check the usage with SDK and apps developers. @JayJay1024 @cinlk

Can this be found on polkadot apps? I don't know which api this `staking::power` refers to
<img width="860" alt="image" src="https://user-images.githubusercontent.com/21007682/173983123-24060115-7738-44f5-bb9e-6eb7808d2884.png">

**Comment by AurevoirXavier** [comment]
> Can this be found on polkadot apps? I don't know which api this `staking::power` refers to <img alt="image" width="860" src="https://user-images.githubusercontent.com/21007682/173983123-24060115-7738-44f5-bb9e-6eb7808d2884.png">

roc staking_power

**Comment by cinlk** [comment]
staking powerOf has been moved to api-derive

**Comment by JayJay1024** [comment]
Darwinia apps does not use this api/rpc
