### ISSUE TITLE
Will state of dispatch precompile be revert if the contract fail/revert?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#1301]
Imagining some contract call dispatch precompile, that dispatch success, but he contract revert and failed finally.

Will the part of dispatch precompile be reverted?

**Comment by AsceticBear** [comment]
Yes, it will.

In the same transaction(call), According to https://github.com/rust-blockchain/evm/blob/master/src/executor/stack/executor.rs#L873-L951 , if something error occurred in the execution, will trigger the `exit_revert` to `rollback_transaction()` at the end of incursive call_inner execution.

```rs
pub fn enter(&mut self, gas_limit: u64, is_static: bool) {
    let mut entering = Self {
        metadata: self.metadata.spit_child(gas_limit, is_static),
        parent: None,
        deletes: BTreeSet::new(),
        logs: Vec::new(),
    };
    mem::swap(&mut entering, self);

    self.parent = Some(Box::new(entering));

    sp_io::storage::start_transaction();
}

pub fn exit_revert(&mut self) -> Result<(), ExitError> {
    let mut exited = *self.parent.take().expect("Cannot discard on root substate");
    mem::swap(&mut exited, self);
    self.metadata.swallow_revert(exited.metadata)?;

    sp_io::storage::rollback_transaction();
    Ok(())
}

```

**Comment by HackFisher** [comment]
Thanks for the explanation.
