### ISSUE TITLE
`internal_transact` needed to call `issueMappingToken`

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-common#1302]
when remote issuing erc20 tokens using sdk, the  `issueMappingToken` function of token factory contract will be called. but `onlySystem` is  allowed to call it. 

so, the `substrate_transact` dispatch_call which call the  `internal_transact` should be implemented. or, a new way is needed.

**Comment by xiaoch05** [comment]
I think we don't need `internal_transact` any more when we use the new design of s2s message SDK.

**Comment by AsceticBear** [comment]
@wuminzhe Is this solved?
