### ISSUE TITLE
Review MaxUsableBalanceFromRelayer, is it too large, or we should use magnitude of gas instead of tokens?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#1310]
> > @hujw77 What's the maximum block gas limit then?
> 
> https://github.com/darwinia-network/darwinia/blob/03c86e1132dce1f6de08decfde2f8a536dd65e79/runtime/crab/src/pallets/evm_.rs#L167

1000000000000 * 2 / 40000 = 50, 000, 000

I think the limitations in message_transact is too generous, or the gas_price is too low currently.

Let's use `50, 000, 000` as the limitation first, maybe in the runtime we should use gas_limit for settings, instead of native tokens.

_Originally posted by @HackFisher in https://github.com/darwinia-network/darwinia-messages-sol/issues/189#issuecomment-1165343840_

**Comment by AsceticBear** [comment]
> Let's use 50, 000, 000 as the limitation first, maybe in the runtime we should use gas_limit for settings, instead of native tokens.

In my understanding, the aim of this max lvalue is to limit the max consumable balance of the relayer by the derived eth account. So just using chain token looks more readable IMO. Perhaps we need to decrease the `MaxUsableBalanceFromRelayer`, 100 COINS is such a large number here.
