### ISSUE TITLE
Should panic or log error while generating genesis if json path is wrong

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/darwinia-common#132]
## Spec

https://github.com/darwinia-network/darwinia/blob/78c06fd4ed27182ee17ae50080ac9fcb16efe07d/bin/node/cli/src/chain_spec.rs#L264

This works fine when we start `darwinia` with `cargo run` but not flexible after we `cargo install .` or just `./darwinia` in the `build-target` directory.

## Panic

And the process will panic when we start `darwinia` with `!carb` network.
```
Thread 'main' panicked at '
!!file NOT FOUND!! current path: /Users/mercury/tmp, load from path: ./bin/node/cli/res/claims_list.json
!!CLAIMS_LIST_PATH var NOT FOUND!!
At least one of them should be VALID
: NotPresent', bin/node/cli/src/chain_spec.rs:158
```

## Solutions

1. It would be nice to start `darwinia` with a specific config file
2. or with one more parameter? seems verbose.
3. recursive dir to find `claims.json` like `rustfmt`
4. write the default json inside `darwinia`

**Comment by HackFisher** [comment]
> > ```
> > export CLAIMS_LIST_PATH $PATH_TO_CLAIMS_LIST
> > ```
> 
> This usage is not friendly, I think we can upgrade it some day.

Should panic or log error, reporting panic, this report the exactly information about the program and then know how to deal with it.

**Comment by clearloop** [comment]
I think it would be nice to embeded a default config in a rust file like `default.rs`, and keep the ENV `CLAIMS_LIST_PATH`, then we can avoid the `panic` thing.

Otherwise, we have to pack `claim_list.json`, `root_merkle.json` to `services/res/xxx.json` into darwinia binary packages like `homebrew`, `snapd`, even `apt` or `yum`

**Comment by AurevoirXavier** [comment]
> I think it would be nice to embeded a default config in a rust file like `default.rs`, and keep the ENV `CLAIMS_LIST_PATH`, then we can avoid the `panic` thing.
> 
> Otherwise, we have to pack `claim_list.json`, `root_merkle.json` to `services/res/xxx.json` into darwinia binary packages like `homebrew`, `snapd`, even `apt` or `yum`

This's just for development. The package that we publish is use for production which means the configurations are already pack in genesis and hard code in the binary.

**Comment by AurevoirXavier** [comment]
I'll add a warning log for dev chain.

**Comment by clearloop** [comment]
> The package that we publish is use for production which means the configurations are already pack in genesis and hard code in the binary.

So the darwinia binary doesn't recommend `--dev`? If anybody want to hack `darwinia`, they have to 

```shell
# download binary
wget https://resourse/darwinia.tar.gz

# extract compressed package
tar -zxvf darwinia.tar.gz

# create config path
mkdir -p services/res/

# download or hanwrite configs
wget https://resourse/claim_list.json services/res/claim_list.json
wget https://resourse/merkle_root.json services/res/merkle_root.json

# run the dev chain
./darwinia --dev
```

**Comment by AurevoirXavier** [comment]
> > The package that we publish is use for production which means the configurations are already pack in genesis and hard code in the binary.
> 
> So the darwinia binary doesn't recommend `--dev`? If anybody want to hack `darwinia`, they have to
> 
> ```shell
> # download binary
> wget https://resourse/darwinia.tar.gz
> 
> # extract compressed package
> tar -zxvf darwinia.tar.gz
> 
> # create config path
> mkdir -p services/res/
> 
> # download or hanwrite configs
> wget https://resourse/claim_list.json services/res/claim_list.json
> wget https://resourse/merkle_root.json services/res/merkle_root.json
> 
> # run the dev chain
> ./darwinia --dev
> ```

If someone want to hack on darwinia, I think they'll get the source code.

**Comment by clearloop** [comment]
And the 

```
# download or hanwrite configs
wget https://resourse/claim_list.json services/res/claim_list.json
wget https://resourse/merkle_root.json services/res/merkle_root.json
```

Doesn't work actually... if they install darwinia as a global command, they have to satisfy

```
$(pwd)/service/res/claim_list.json
$(pwd)/service/res/merkle_root.json
```
in the path where they `exec` the `darwinia` command.

---

> > ```
> > export CLAIMS_LIST_PATH $PATH_TO_CLAIMS_LIST
> > ```
> 
> This usage is not friendly, I think we can upgrade it some day.

This comment actually means the situation above...

---

> If someone want to hack on darwinia, I think they'll get the source code.

Well I was trying to hack `eth-relay` on darwinia, and failed last night ; (

> Unless they want to hack on eth-relay and darwinia-claims.

`Relay` is one of the biggest features of darwinia, if developers don't hack `relay`, what should they hack? This is not supposed be ignored.

**Comment by AurevoirXavier** [comment]
If developers hack on relay, they already get the source code. DO NOT need `wget` etc.

**Comment by clearloop** [comment]
> If developers hack on relay, they already got the source code. DO NOT need `wget` etc.

This design just make the `--dev` flag in the release version of darwinia binary not necessary...

**Comment by AurevoirXavier** [comment]
For front end, for balances, for staking...?

Also the claims list are private, other people CAN NOT use that.

Anyway, I'll add some default dag nodes for eth-relay.

**Comment by clearloop** [comment]
> For front end, for balances, for staking...? --dev is always necessary.

These features are available for any `substrate-based` chains actually, if developers just hack these features, why should they choose `darwinia`?

**Comment by AurevoirXavier** [comment]
No, all the pallet in darwinia are different from substrate with specify features.

Recommend you to read the code. (Otherwise, why we implment it again???)

**Comment by clearloop** [comment]
> Recommend you to read the code first. (Otherwise, why we implement it again???)

Not all new developers will read the source code, once they know a new `blockchain`, they are learning it from the concepts in their minds, not the source code.

**Comment by AurevoirXavier** [comment]
The gene paper and other docs also tell you our feature are different from substrate. It's worth to develop.


> Recommend you to read the code first. (Otherwise, why we implement it again???)


Just because I assume you're the darwinia developer.

---

Those things are not the topic about this issue. So stop here :)
