### ISSUE TITLE
Upstream stack runner check `if total_fee > U256::zero()` looks not good and not necessary

### ISSUE THREAD

**Issue by hackfisher** [darwinia-network/darwinia-common#1386]
OK, but the upstream check `if total_fee > U256::zero()` looks not good and not necessary to me.

_Originally posted by @HackFisher in https://github.com/darwinia-network/darwinia-common/pull/1326#discussion_r941112661_

**Comment by HackFisher** [comment]
Related: https://github.com/paritytech/frontier/blob/0181f81f113729dbf8e013f81d13f619f3eee74a/frame/evm/src/runner/stack.rs#L96-L105

**Comment by HackFisher** [comment]
Might be gone in latest master branch
