### ISSUE TITLE
The new contract  address of CKTON

### ISSUE THREAD

**Issue by ZolaxZola** [darwinia-network/darwinia-common#1395]
`0x0000000000000000000000000000000000000402`
After filling the contract address above, the Token Symbol doesn't show up as expected, is there something wrong?

![image](https://user-images.githubusercontent.com/102211220/184080240-07660d45-2d58-46bf-ae68-52380693f2a3.png)

**Comment by AsceticBear** [comment]
Did you test this in the crab network? This feature doesn't include in the crab runtime now. Please try the pangolin first.

**Comment by ZolaxZola** [comment]
OK, understood!

**Comment by AsceticBear** [comment]
If you test that works, please close this issue later.

**Comment by ZolaxZola** [comment]
It works on Pangolin Network.
