### ISSUE TITLE
blur private key

### ISSUE THREAD

**Issue by LiRiu** [darwinia-network/darwinia-common#1406]
https://github.com/darwinia-network/darwinia-common/blob/cd427678aeb4f10052dcb00f692403c0e2e9d338/tests/dvm/frontier/tests/test-pending-pool.ts#L8

**Comment by AsceticBear** [comment]
It is a well-known test key pair, like Alice or Bob in the substrate. So I am gonna close it. 

See https://docs.crab.network/evm-compatible-crab-smart-chain/get-started/darwinia-dev#pre-funded-development-accounts
