### ISSUE TITLE
Can not relay message root after authority changes.

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-common#1411]
https://github.com/darwinia-network/darwinia-common/blob/693910c378c1e8225c843c7deca2ab5f2e25cf80/frame/bridge/ecdsa-authority/src/lib.rs#L498

**Comment by AurevoirXavier** [comment]
We could emit a new message root immediately after the authorities changed.

**Comment by hujw77** [comment]
> We could emit a new message root immediately after the authorities changed.

Nice proposal!

**Comment by AurevoirXavier** [comment]
We also could insert the message root into the authority change message.
