### ISSUE TITLE
Migration for darwinia-eth-linear-relay

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#157]

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia-common/pull/155#pullrequestreview-426813665

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia-common/pull/155/files#diff-e42049292451ec7f53c198d8e2b0c572R6

```eth-backing``` has been changed to ```ethereum-backing```, need migration too.
