### ISSUE TITLE
elections-phragmen Voting> free_balance corner cases?

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#161]

**Comment by yanganto** [comment]
Once the validator bond all his value, he should still have the right to vote the things and provide his opinions in the Democracy pallet, so the bond in staking should not affect the bond on the Democracy pallet.

**Comment by HackFisher** [comment]
> Once the validator bond all his value, he should still have the right to vote the things and provide his opinions in the Democracy pallet, so the bond in staking should not affect the bond on the Democracy pallet.

I think it depends, for the voting here, we was planning to use the staking ```Power``` value for voting, so it already reuse the bonds.

For other cases,  I think we should discourage using same bond in two slash scenes, such as relayer bond and validator bond, they all have slash possibilites, if the bond is slashed in one space, it will not work as expeceted in another space as bond.

**Comment by AurevoirXavier** [comment]
Use free balance to suit substrate modules' lock.

**Comment by AurevoirXavier** [comment]
```rust
Some(
    StakingLedger {
        stash: 123,
        active_ring: 0,
        active_deposit_ring: 0,
        active_kton: 1,
        deposit_items: [],
        ring_staking_lock: StakingLock {
            staking_amount: 0,
            unbondings: [],
        },
        kton_staking_lock: StakingLock {
            staking_amount: 1,
            unbondings: [
                Unbonding {
                    amount: 2,
                    until: 10,
                },
                Unbonding {
                    amount: 6,
                    until: 10,
                },
            ],
        },
        claimed_rewards: [],
    },
)
Start
T::KtonCurrency::free_balance(&stash): 2, T::KtonCurrency::usable_balance(&stash): 1, ledger.total_kton(): 9, max_additional: 1
```

```rust
T::KtonCurrency::free_balance(&stash): 10, T::KtonCurrency::usable_balance(&stash): 5, k: 4
Some(
    StakingLedger {
        stash: 123,
        active_ring: 0,
        active_deposit_ring: 0,
        active_kton: 1,
        deposit_items: [],
        ring_staking_lock: StakingLock {
            staking_amount: 0,
            unbondings: [],
        },
        kton_staking_lock: StakingLock {
            staking_amount: 1,
            unbondings: [
                Unbonding {
                    amount: 2,
                    until: 10,
                },
                Unbonding {
                    amount: 6,
                    until: 10,
                },
            ],
        },
        claimed_rewards: [],
    },
)
Start
T::KtonCurrency::free_balance(&stash): 2, T::KtonCurrency::usable_balance(&stash): 1, k: 1
```

**Comment by HackFisher** [comment]
Use reserve for non-overlapping bonds, use lock when need overlap. Staking Ledger and elections-phragmen voting are using locks, if staking get slashed, there might be cases that Voting> free_balance , If there is enough free_balance for slash, normally it may not affect the Voting Lock.
