### ISSUE TITLE
Using Merkle Tree to verify blocks along with Merkle Mountain Tree Concept in Ethereum Relay process.

### ISSUE THREAD

**Issue by clearloop** [darwinia-network/darwinia-common#178]
# Ethereum Relayer Game minus

The MMR Proof in Ethereum Relay makes Darwinia cross-chain storage quite like a `client` of `Ethereum`, though the relaying blocks need to be part of Ethereum Merkle Mountain Tree, the verify processing doesn't have to be.

## Why this solution?

In a Relayer Game Proposal, Along with we can calculate out the `mmr_size` of the little Merkle Mountain Tree which the confirm-need block in,  we can calculate the positions of the leaves of the confirm-need block.

Every little mountain of a Merkle Mountain Tree is a Merkle Tree, that's why we can prove straight down also.

## What if the confirm-need block is a leaf?

Since the current Height of Ethereum Block is `10419380`, the leaf situation rarely happens, but still have.

Generate a fake Merkle Tree constructed by random relayed Ethereum blocks, prove them in the same way as before, the Merkle Tree proof algorithm will work as before, just require different blocks.

## Difference

Store the `mmr_root` field of every relaying block, prove blocks by this value in the Merkle Tree proof algorithm, doesn't need the proof common MMR Tree generates.

## Why `mmr_root`?

This field keeps the feature of Merkle Mountain Tree, so we can find the shortest proof while the confirm-need block is not a leaf.

# Example - A modification of current relayer game

- **Target Chain: Ethereum**
- **Sampling Strategy: One By One**
- **Relay Block's Position in Ethereum MMR: `15`**
- **Game Id: 15**
- **Last Confirmed Block's Position on Darwinia When Game(15) Started: 7**
- **The Proof Order is From Top to Foot, then Left to Right**

```text
           15 
        /     \ 
     7           14                     
   /   \       /    \             
  3     6    10     13     
 / \   / \   / \   /  \     
1   2 4   5 8   9 11  12  
```

| Round | Proof |
|:-:|:-:|
| a | `7, 14` |
| b | `3, 6` |
| c | `10, 13` |
| d | `1, 2` |
| e | `4, 5` |
| f | `8, 9`|
| g | `11, 12`|

**Comment by HackFisher** [comment]
It seems that position is confused with block number. The devil is in the details.

> - **Last Confirmed Block's Number on Darwinia When Game(15) Started: 7**
> - **The Proof Order is From Foot to Top, then Left to Right**
> 
> ```text
>            15 
>         /     \ 
>      7           14                     
>    /   \       /    \             
>   3     6    10     13     
>  / \   / \   / \   /  \     
> 1   2 4   5 8   9 11  12  
> ```
> 
> | Round | Proof |
> |:-:|:-:|
> | a | `7, 14` |

What's the numbers in the tree graph? Block number or MMR node positions?

If they are node positions, then in the round a, we need the proof that block 7(node 11) is include in the MMR with last leaf block 15(node ?, node included in the tree), how could we generate the proof?

 ```text
                    15 
                 /     \ 
              7           14                     
            /   \       /    \             
           3     6    10     13     
          / \   / \   / \   /  \     
         1   2 4   5 8   9 11  12  
block   1   2 3   4 5   6 7   8
 ```

**Comment by clearloop** [comment]
> The devil is in the details.

Position...yep, need an algorithm to convert the positions above to block numbers.

**Comment by HackFisher** [comment]
> > The devil is in the details.
> 
> 
> 
> Position...yep, need an algorithm to convert the positions above to block numbers.

How?? Not every node position can be converted to block number, some are merged branch node.

Please tell the detail here.

**Comment by clearloop** [comment]
> Please tell the detail here.

It was my mistake, I just don't have enough patience to understand something from others unless I implement them step by step like this by my self. XDD
