### ISSUE TITLE
Refactor suggestions regarding relay modules

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#188]
1. EthereumRelay implements EthereumRelayabe
2. Dispatch calls are all put into EthereumRelay, relay_header(EthereumHeaderThing). The parameter EthereumHeaderThing uses EthereumRelayabe codec into vec<v8> and is passed to RelayerGame’s submit_proposals. When using it, adjust the EthereumRelayabe interface. In this way, both apps and explorer can easily analyze the EthereumHeaderThing Type
3. As a more general and closed module, RelayerGame can manage its own storage, events and on_initialize/on_finalize, which are related to verifying the game sub-protocol.
4. EthereumRelay Dispatch Call calls RelayerGame to complete tasks related to verifying game sub-protocols.

**Comment by HackFisher** [comment]
ConfirmBlockManagementError should be a Error, not a event.

**Comment by AurevoirXavier** [comment]
Currently, the implementation is very ugly, very Inefficiency. 

Relay encode the header pass to Game, then Game call Relay to decode it. Such as `verify_raw_header_thing` is unnecessary. 

We should eventually separate the APIs. Refactor the Game's protocol

**Comment by clearloop** [comment]
It might be a solution to implement a struct named `Relayable`:

```rust
struct Relayable {}

struct EthereumHeaderThing {}
struct TronHeaderThing{}

impl Into<Relayable> for EthereumHeaderThing{}
impl Into<Relayable> for TronHeaderThing{}
```

Or use a trait and proc_macro

```rust
struct Relayable {
  header: String,
  mmr: H256,
}

trait RelayableTrait {
   fn relayable() -> Relayable
}

/// -snippet-
/// a proc macro

#[derive(Relayable)]
struct EthHeaderThing{}

#[derive(Relayable)]
struct TronHeaderThing{}

```

**Comment by HackFisher** [comment]
> Currently, the implementation is ugly, very inefficiency.
> 
> Relay encode the header things pass to Game, then Game call Relay to decode them. Such as `verify_raw_header_thing`, `verify_raw_header_things` are unnecessary under this architecture.
> 
> We should eventually separate the APIs. Refactor the Game's protocol.
> 
> Is possible to make Game an actual protocol? Like phragmen which defined in primitives.

Can we remove ```RawHeaderThing``` and make ```HeaderThing``` an associate type for both Relay and RelayerGame?

Then for ```EthereumRelay```, we can assign ```EthereumHeaderThing``` to this associate type, for ```TronRelay```, we can assign ```TronHeaderThing```.

We will not need encode/decode process between them then.

Currently RelayerGame has chain storages, it's more like a pallet than a primitives library.
