### ISSUE TITLE
Refactoring Eth-Relay and Eth-Backing Tests

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#19]
- [x] Testing canonical header re-org, related to darwinia-network/darwinia#302
- [x] Block Safe for verification receipt darwinia-network/darwinia#313 
- [x] Testing for RingReward / KtonReward, current reward OnUnbalance is set to (), and imblance when on_unbalance should be zero after redeeming, because balance are transfer to target redeem account

**Comment by HackFisher** [comment]
+ [ ] subkey prefix parameterize using module associate type
+ [ ] network constant and parameterize
