### ISSUE TITLE
Security audit

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#2]
### Any PR is welcome. If you got confused feel free to contact the code owners.

- [ ] /bin/node-template/node/ @AurevoirXavier
- [ ] /bin/node-template/runtime/ @AurevoirXavier

- [ ] /client/cli/ @AurevoirXavier

- [ ] /frame/balances/ @AurevoirXavier @HackFisher
- [ ] /frame/balances/rpc/ @AurevoirXavier
- [ ] /frame/balances/rpc/runtime-api/ @AurevoirXavier

- [ ] /frame/bridge/crab/issuing @AurevoirXavier @HackFisher
- [ ] /frame/bridge/ethereum/backing/ @AurevoirXavier @HackFisher
- [ ] /frame/bridge/ethereum/linear-relay/ @AurevoirXavier @clearloop @HackFisher
- [ ] /frame/bridge/ethereum/offchain/ @AurevoirXavier @yanganto
- [ ] /frame/bridge/ethereum/relay/ @AurevoirXavier @HackFisher @yanganto
- [ ] /frame/bridge/relayer-game/ @AurevoirXavier @yanganto

- [ ] /frame/claims/ @AurevoirXavier @HackFisher

- [ ] /frame/elections-phragmen/ @AurevoirXavier

- [ ] /frame/header-mmr/ @AurevoirXavier @clearloop @HackFisher

- [ ] /frame/staking/ @AurevoirXavier @HackFisher
- [ ] /frame/staking/rpc/ @AurevoirXavier
- [ ] /frame/staking/rpc/runtime-api/ @AurevoirXavier

- [ ] /frame/support/ @AurevoirXavier @HackFisher

- [ ] /frame/treasury/ @AurevoirXavier @clearloop @HackFisher

- [ ] /primitives/array-bytes/ @AurevoirXavier
- [ ] /primitives/ethereum-primitives/ @AurevoirXavier @HackFisher
- [ ] /primitives/relay/ @AurevoirXavier
- [ ] /primitives/merkle-patricia-trie/ @HackFisher

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia/wiki/Best-Practice-for-Darwinia-Security-Review

**Comment by HackFisher** [comment]
And we need a SECURITY doc like substrate's, github public issues might not be the best channel for reporting vulnerabilities, its better to use email.

https://github.com/paritytech/substrate/blob/master/docs/SECURITY.md
