### ISSUE TITLE
Node template panicked at 'Authorities are already initialized!'

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#22]
./target/release/node-template --dev            
2020-03-28 11:25:57 Running in --dev mode, RPC CORS has been disabled.
2020-03-28 11:25:57 Substrate Node
2020-03-28 11:25:57   version 0.5.0-d32735f-x86_64-macos
2020-03-28 11:25:57   by Anonymous, 2017-2020
2020-03-28 11:25:57 Chain specification: Development
2020-03-28 11:25:57 Node name: furry-grandmother-6169
2020-03-28 11:25:57 Roles: AUTHORITY

====================

Version: 0.5.0-d32735f-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: std::panicking::begin_panic
   5: pallet_grandpa::Module<T>::initialize_authorities
   6: <(TupleElement0, TupleElement1, TupleElement2) as pallet_session::SessionHandler<AId>>::on_genesis_session
   7: std::thread::local::LocalKey<T>::with
   8: sp_state_machine::basic::BasicExternalities::execute_with_storage
   9: <node_template_runtime::GenesisConfig as sp_runtime::BuildStorage>::assimilate_storage
  10: sp_runtime::BuildStorage::build_storage
  11: <sc_chain_spec::chain_spec::ChainSpec<G,E> as sp_runtime::BuildStorage>::build_storage
  12: sc_client::client::Client<B,E,Block,RA>::new
  13: sc_client_db::new_client
  14: sc_service::builder::ServiceBuilder<(),(),(),(),(),(),(),(),(),(),()>::new_full
  15: node_template::service::new_full
  16: sc_cli::runtime::run_service_until_exit
  17: node_template::command::run
  18: node_template::main
  19: std::rt::lang_start::{{closure}}
  20: std::panicking::try::do_call
  21: __rust_maybe_catch_panic
  22: std::rt::lang_start_internal
  23: main

Thread 'main' panicked at 'Authorities are already initialized!', <::std::macros::panic macros>:2

This is a bug. Please report it at:

        support.anonymous.an

**Comment by AurevoirXavier** [comment]
Try remove the imonline auth in chain spec, if still happen, remove the grandpa auth also.
