### ISSUE TITLE
Enhance the depedency ensure scipt

### ISSUE THREAD

**Issue by yanganto** [darwinia-network/darwinia-common#23]
There are several parts in the project, it is good to let every part clean and loose coupled.  So we use `darwinia_ensure_deps.sh` to help developer to make the dependency clean and loose coupled.  

However, the script is not flexible enough for more complicate folder structure.  Please helping us to do this.  If you have any problem, you may chat with us on Telegram or Riot.  
Thanks.

https://github.com/darwinia-network/darwinia-common/blob/master/.maintain/darwinia-ensure-deps.sh#L36

**Comment by AurevoirXavier** [comment]
Not sure if we need this.

https://github.com/paritytech/substrate/blob/master/.maintain/ensure-deps.sh
