### ISSUE TITLE
Update Labels

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#240]
We should mark some PR as `runtime-migration`, `remove-migration` and more...

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia-common/labels/D1-runtime-migration

https://github.com/darwinia-network/darwinia-common/labels/D2-remove-migration

**Comment by HackFisher** [comment]
@AurevoirXavier Updated the privilege and access, you should able to manage labels directly now.
