### ISSUE TITLE
EVM Support Solution

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#247]
Latest discussion and solution:

- [ ] Replacing Account20(EVM Contract Address) to AccountID32 using hash_concat instead of directly hashing.
- [ ] For Account32(subkey) to AccountID20 conversion, using ```cut````
- [ ] Using eddsa for evm call instead of ecdsa, so we can sign evm related txs using polkadot{.js} exention or other polkadot.js private key provider
- [ ] EVM and Substrate toolchains support: For web3.js, metamask, web3 rpc, remix(solidity ide) etc, we might need to to some forking to support eddsa sign.
- [ ] User only need to care about AccountID32 address, developers might need to know AccountID20(evm address)

Question:

Can ecdsa and eddsa share same key pair(for easier wallet support)?

Refer:

Frontier: Using two separate crypto algorithm (eddsa for substrate runtime, ecdsa for evm inside?)
https://github.com/paritytech/frontier

Moonbeam:

Question: Will use ecdsa instead of eddsa(sr25519)? and H160? Could ecdsa have compatibility issues with Polkadot Parachain?

Substrate Seminar

https://www.crowdcast.io/e/substrate-seminar/9

**Comment by HackFisher** [comment]
https://wiki.polkadot.network/docs/en/learn-keys#why-was-ed25519-selected-over-secp256k1

**Comment by HackFisher** [comment]
Related: https://github.com/darwinia-network/darwinia/issues/496

**Comment by wuminzhe** [comment]
the code maybe like this:
```
hash_concat(evm_address) -> subkey {
    return evm_address + blake2256(evm_address)[0..12]
}
```

**Comment by freehere107** [comment]
https://github.com/polkadot-js/api/issues/2499#issuecomment-678765191

**Comment by AsceticBear** [comment]
#334

**Comment by HackFisher** [comment]
This is deprecated solution, for latest update please see https://github.com/darwinia-network/darwinia-common/pull/334
