### ISSUE TITLE
New EthereumReceiptProof Sample for receipt verify tests

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#262]

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia-common/pull/259
https://github.com/darwinia-network/darwinia-common/issues/260

**Comment by HackFisher** [comment]
I'm using tx for testing:
https://github.com/darwinia-network/dj#tx-on-the-ethereum-ropsten-test-network

https://testnet.shadow.darwinia.network/eth/receipt/0x1d3ef601b9fa4a7f1d6259c658d0a10c77940fa5db9e10ab55397eb0ce88807d/8610361

But there are some issue with the etherum rpc for receipt, geth(fast model) is not working, need to change to infura.
