### ISSUE TITLE
Last comfirmed header maybe different in first proposal submit of relayer game

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-common#266]
https://github.com/darwinia-network/darwinia-common/blob/af67af0748019e125a6b069af84e2a933f32b0ba/frame/bridge/ethereum/relay/src/lib.rs#L474

**Comment by HackFisher** [comment]
Related https://github.com/darwinia-network/darwinia-common/pull/268

**Comment by HackFisher** [comment]
https://github.com/darwinia-network/darwinia-common/blob/4e3ecee7c91837ee18b5703b89e7ad81e779d747/frame/bridge/ethereum/relay/src/lib.rs#L419
