### ISSUE TITLE
Any documentation for this repo?

### ISSUE THREAD

**Issue by herou** [darwinia-network/darwinia-common#269]
Hello,

Is there any documentation for this repo that I can take a look at?

**Comment by AurevoirXavier** [comment]
I think there is no.

Heavily in development.

@clearloop Is darwinia-book out-dated?

**Comment by clearloop** [comment]
> I think there is no.
> 
> Heavily in development.
> 
> @clearloop Is darwinia-book out-dated?

Yep, it is, but maybe we can cook it together @herou : )

**Comment by herou** [comment]
> > I think there is no.
> > Heavily in development.
> > @clearloop Is darwinia-book out-dated?
> 
> Yep, it is, but maybe we can cook it together @herou : )

Why not @clearloop. Please tell me more...

**Comment by clearloop** [comment]
> Why not @clearloop. Please tell me more...

[This][0] is the old book, 3 points here:

## 1. Some docs about the substrate ecology is quite complete
+ Substrate
  + Substrate [receipes][1], the wonderful one
  + The official API reference, [docs.rs][2]
+ Darwinia
  + [WIKI][3] of Darwinia
  + Run `cargo doc` under `darwinia` or `darwinia-common` project

It's hard to determine which kind of docs is completely necessary for us to keep writing on, though we know there must be some better one.

## 2. The arch of Darwinia is changing

We are iterating blazing fast that it is hard to catch up.

## 3. Don't have enough time

This point is why we need more and more people like you to join us : )



[0]: https://darwinia-network.github.io/the-darwinia-book/
[1]: https://substrate.dev/recipes/
[2]: https://substrate.dev/rustdocs/v2.0.0-rc6/sc_service/index.html
[3]: https://docs.darwinia.network/docs/en/wp-home

**Comment by herou** [comment]
> > Why not @clearloop. Please tell me more...
> 
> [This](https://darwinia-network.github.io/the-darwinia-book/) is the old book, 3 points here:
> 
> ## 1. Some docs about the substrate ecology is quite complete
> * Substrate
>   
>   * Substrate [receipes](https://substrate.dev/recipes/), the wonderful one
>   * The official API reference, [docs.rs](https://substrate.dev/rustdocs/v2.0.0-rc6/sc_service/index.html)
> * Darwinia
>   
>   * [WIKI](https://docs.darwinia.network/docs/en/wp-home) of Darwinia
>   * Run `cargo doc` under `darwinia` or `darwinia-common` project
> 
> It's hard to determine which kind of docs is completely necessary for us to keep writing on, though we know there must be some better one.
> 
> ## 2. The arch of Darwinia is changing
> We are iterating blazing fast that it is hard to catch up.
> 
> ## 3. Don't have enough time
> This point is why we need more and more people like you to join us : )

@clearloop Thank you for replying to me back. I have to read point 3 in the old book and the wiki page. I have already read the substrate recipe and I am a contributor to that repo. I will ping you once I am done.

**Comment by herou** [comment]
> > > Why not @clearloop. Please tell me more...
> > 
> > 
> > [This](https://darwinia-network.github.io/the-darwinia-book/) is the old book, 3 points here:
> > ## 1. Some docs about the substrate ecology is quite complete
> > 
> > * Substrate
> >   
> >   * Substrate [receipes](https://substrate.dev/recipes/), the wonderful one
> >   * The official API reference, [docs.rs](https://substrate.dev/rustdocs/v2.0.0-rc6/sc_service/index.html)
> > * Darwinia
> >   
> >   * [WIKI](https://docs.darwinia.network/docs/en/wp-home) of Darwinia
> >   * Run `cargo doc` under `darwinia` or `darwinia-common` project
> > 
> > It's hard to determine which kind of docs is completely necessary for us to keep writing on, though we know there must be some better one.
> > ## 2. The arch of Darwinia is changing
> > We are iterating blazing fast that it is hard to catch up.
> > ## 3. Don't have enough time
> > This point is why we need more and more people like you to join us : )
> 
> @clearloop Thank you for replying to me back. I have only to read point 3 in the old book and the wiki page because I have already read the substrate recipe and I am a contributor to that repo. I will ping you once I am done.

Well, I took a look at the wiki page and point #3 of the old book. What is next?

**Comment by clearloop** [comment]
> What is next?

Currently, we have no explicit plan about the next version, maybe you can mail @AlexChien if you have interests in it. You can rewrite the whole book if you've already got some great ideas, and we'll join you if you need our help, nevermind :-p

BTW, maybe you don't have to reference all comments in your comments, it too long XDD, sincerely.

**Comment by herou** [comment]
> > What is next?
> 
> Currently, we have no explicit plan about the next version, maybe you can mail @AlexChien if you have interests in it. You can rewrite the whole book if you've already got some great ideas, and we'll join you if you need our help, nevermind :-p
> 
> BTW, maybe you don't have to reference all comments in your comments, it too long XDD, sincerely.

I can start to help with the small tickets if you want. Small bug fixes etc

**Comment by herou** [comment]
I am closing this issue because I understand that you are not looking for a contributor to help you out. From the documentation I understood that Darwinia is a great project which I would like to give a hand but it seems you do not welcome any contributors.

**Comment by clearloop** [comment]
I'll try to re-arch the book tomorrow, and maybe we can talk on that repo late days~

Besides, would you like to write an article about [relayer-game][0], this is actually the core part of Darwinia, and if you have any concepts misunderstand, just ping @AurevoirXavier 

@herou 



[0]: https://github.com/darwinia-network/darwinia-common/tree/master/frame/bridge/relayer-game

**Comment by herou** [comment]
> I'll try to re-arch the book tomorrow, and maybe we can talk on that repo late days~
> 
> Besides, would you like to write an article about [relayer-game](https://github.com/darwinia-network/darwinia-common/tree/master/frame/bridge/relayer-game), this is actually the core part of Darwinia, and if you have any concepts misunderstand, just ping @AurevoirXavier
> 
> @herou

Do you have any public group chat where I can contact @AurevoirXavier ?

**Comment by clearloop** [comment]
> I am closing this issue because I understand that you are not looking for a contributor to help you out. 

We really need contributors, sorry for letting you thinking of that.

For some reasons, we haven't set up a mature contribution system yet, we're understaffed these days...for example, @AurevoirXavier is busy with developing [darwinia-network/dariwinia][darwinia], and I'm busy with developing [darwinia-network/shadow][shadow] and [darwinia-network/dj][dj]...every project of Darwinia is pushing fast.

> Do you have any public group chat where I can contact @AurevoirXavier ?

Yep, [Telegram][tg] and [Riot][riot] on your option~


[darwinia]: https://github.com/darwinia-network/darwinia
[shadow]: https://github.com/darwinia-network/shadow
[dj]: https://github.com/darwinia-network/darwinia/dj
[tg]: https://t.me/DarwiniaDev
[riot]: https://matrix.to/#/!HIyWQGUzgpkxswYMNi:matrix.org?via=matrix.org

**Comment by herou** [comment]
> > I am closing this issue because I understand that you are not looking for a contributor to help you out.
> 
> We really need contributors, sorry for letting you thinking of that.
> 
> For some reasons, we haven't set up a mature contribution system yet, we're understaffed these days...for example, @AurevoirXavier is busy with developing [darwinia-network/dariwinia](https://github.com/darwinia-network/darwinia), and I'm busy with developing [darwinia-network/shadow](https://github.com/darwinia-network/shadow) and [darwinia-network/dj](https://github.com/darwinia-network/darwinia/dj)...every project of Darwinia is pushing fast.
> 
> > Do you have any public group chat where I can contact @AurevoirXavier ?
> 
> Yep, [Telegram](https://t.me/DarwiniaDev) and [Riot](https://matrix.to/#/!HIyWQGUzgpkxswYMNi:matrix.org?via=matrix.org) on your option~

I am sorry that you have not a mature contribution system, in order to have more staff you need to give the others the possibility to contribute but this is another topic.
