### ISSUE TITLE
verified's receipt should not limit the mmr_root block number to last confirmed

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#273]
https://github.com/darwinia-network/darwinia-common/blob/master/frame/bridge/ethereum/relay/src/lib.rs#L628

Currently,  ```MMRProof``` is
```
pub type MMRProof = Vec<H256>;
```

should be refactored to something like 

```
pub struct MMRProof {
   // member leaf
   u64 member_block_number,
   // the number of the block attaching mmr root
   u64 mmr_root_block_number,
   // mmr proof generated
   Vec<H256>
}
```

**Comment by AurevoirXavier** [comment]
OK.

**Comment by HackFisher** [comment]
```Self::last_confirmed_header_info()``` need to be replace with ```mmr_root_block_number ```, and check that ```mmr_root_block_number ``` is confirmed in the relay history blocks.

Let's do it in next runtime.
