### ISSUE TITLE
More Cases for Total Difficulty Checking

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#280]

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia-common/blob/fb09dd55a2/frame/bridge/ethereum/relay/src/lib.rs#L741

**Comment by HackFisher** [comment]
There are some other checks: https://github.com/darwinia-network/darwinia-common/blob/fb09dd55a27e8c668e173e07ce840ab852ed7d7c/frame/bridge/ethereum/linear-relay/src/lib.rs#L637

But it may not easy to do in relayer game.
