### ISSUE TITLE
Adding compute_kton_retrun testcase

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#298]

**Comment by HackFisher** [comment]
https://github.com/evolutionlandorg/bank/blob/master/contracts/GringottsBank.sol#L280

**Comment by AurevoirXavier** [comment]
https://talk.darwinia.network/topics/55

**Comment by AurevoirXavier** [comment]
https://docs.darwinia.network/docs/en/wiki-us-tokens
