### ISSUE TITLE
[EVM] A precompile contrate to transfer the balance from the EVM account to the substrate account.

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/darwinia-common#319]
Question: Is it necessary to reconstruct the input format included `FROM`, `TO`, `VALUE` to adapt to `Trait Precompile`?

**Comment by wuminzhe** [comment]
call from solidity:
https://github.com/darwinia-network/darwinia-common/blob/e4b837be7ec1dc4917aa1fe6c94375a45b74ea9a/bin/node-template/runtime/src/lib.rs#L1067

```solidity
pragma solidity ^0.6.0;

contract Test1 {

  function transferBack() public view {
    bytes32[3] memory output;
    bytes32[3] memory h;
    h[0] = hex"000000000000000000000000182c00A789A7cC6BeA8fbc627121022D6029a416";
    h[1] = hex"d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d";
    h[2] = hex"0000000000000000000000000000000000000000000000000000000000221388";
    // h[3] = sign
    bytes memory input = abi.encodePacked(h[0], h[1], h[2]);
    assembly {

      if iszero(staticcall(not(0), 0x1, input, 0x80, output, 0x40)) {
        revert(0, 0)
      }
    }
  }
}
```

https://github.com/ethereum/EIPs/blob/master/EIPS/eip-152.md#example-usage-in-solidity

**Comment by AsceticBear** [comment]
#334

**Comment by AurevoirXavier** [comment]
Can close now?

**Comment by WoeOm** [comment]
`// h[3] = sign `
Why is there no need to verify the signature?
@wuminzhe

**Comment by AsceticBear** [comment]
Pre-compiled contracts do not have access to the from values of transactions and cannot resist relay attacks, so this solution is abandoned.
