### ISSUE TITLE
The storage solutions for different precision between evm and darwinia

### ISSUE THREAD

**Issue by AsceticBear** [darwinia-network/darwinia-common#352]
Due to the difference in currency decimal between Darwinia and Ethereum, we hope to provide a storage solution to better achieve balance transfer.

**Comment by AsceticBear** [comment]
I issue the problems I encountered so far when attempts to implements the storage solution.

1. Firstly,  A new trait with two methods created in the substrate evm pallet.

```rs
pub trait AccountMatching {
	fn account_basic(address: &H160) -> Account;
	fn mutate_account_basic(address: &H160, new: Account);
}
```

2. Let the native method implementations as default trait behavior in evm pallet, then add newly created trait to evm pallet trait as associated type.

```rs
impl frame_evm::Trait for Runtime {
	....
	type ChainId = ChainId;

        // You could custom your own account match way
	type AccountMatching = DVMAccountMatching<Self>;
}
```

---

The confusion now lies in the storage implementation, I tried two ways:

*A*: Hack the newly created trait
```rs
pub trait AccountMatching {
	// This One
	type RemainingBalanceStore: StoredMap<Self::AccountId, pallet_balances::AccountData<u64>>;
	
	fn account_basic(address: &H160) -> Account;
	fn mutate_account_basic(address: &H160, new: Account);
}
```
In this way, we also need to add a default `RemainingBalanceStore` for the default `AccountMatching` implementation in evm pallet.


*B*: Hack on the EVM module trait.

```rs
/// EVM module trait
pub trait Trait: frame_system::Trait + pallet_timestamp::Trait {
	....
	type AccountMatching: AccountMatching;
	// This One
	type RemainingBalanceStore: StoredMap<Self::AccountId, pallet_balances::AccountData<u64>>;
}
```

This way will add two items in the EVM module trait. 

Maybe there are more clever ways to achieve this, please let me know.


*Another question:* 

How can I set the Value type in `StoredMap`  to ensure the least impact on the evm pallet and be compatible with darwinia chain at the same time?

**Comment by HackFisher** [comment]
For A, remove associate type RemainingBalanceStore, and implement it in Runtime, you will be able you call other module directly in runtime, e.g. using their storage.

**Comment by AsceticBear** [comment]
> you will be able you call other module directly from the type implementation in runtime, e.g. using other module's storage.

That's amazing,  let me have a try.

**Comment by HackFisher** [comment]
Refer
https://github.com/darwinia-network/darwinia/blob/f5f4fca2fd7044ba51b491cd77d1f0e9764090ba/runtime/darwinia/src/lib.rs#L529
