### ISSUE TITLE
Remove Bootstrap Script

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#354]
https://github.com/darwinia-network/darwinia-common/blob/master/.maintain/bootstrap.sh

**Comment by HackFisher** [comment]
Do we still need to keep this `bootstrap.sh`, or we should directly remove it.

Not used by anyone as there are latest updated guide from substrate and darwinia.

**Comment by AsceticBear** [comment]
Agreed!
