### ISSUE TITLE
DVM update trace

### ISSUE THREAD

**Issue by AsceticBear** [darwinia-network/darwinia-common#362]
## UPDATE LIST

<details>
<summary> ~ 2021.04.09</summary>

- [x] Decouple Runtime API impls from specific structs (167) 
- [x] Return correct response in `eth_syncing` (164)
- [x] Fix eth_estimateGas and eth_call to match with Ethereum impl (168) 
- [ ] Support instant sealing (170)  ***Skip***
- [x] Use the new Runner trait from pallet-evm (162)
- [x] Fix RPC call when gas price is not provided (172)
- [x] estimate_gas should handle exit reason (174)
- [ ] Add GitHub Action to Publish Rustdocs as GitHub Page (179) ***Skip***
- [ ] Add GitHub Issue Templates (183)  ***Skip***
- [x] Pending nonce (176) 
- [x] Update evm version (187)
- [x] EVM execution error should not result in DispatchError (188)
- [ ] Tests transaction receipts for reverted evm execution (184) ***Skip***
- [x] Update ethereum version for correct transactiImprove binary search algorithm for gas estimation.on root calculation (191)
- [x] Custom signer support (196)
- [ ] Implement dev signer (197) ***Skip***
- [x] Set `logs_bloom` (200)
- [x] Add weight annotation to pallet Ethereum's transact extrinsic (202)
- [x] Add hex-encoded IdProvider (203)
- [x] Add `net_peerCount` implementation (204)
- [x] Implement `Web3Api` (205)
- [x] pallet-evm: move to Frontier (Part I) (206)
- [x] pallet-evm: move to Frontier (Part II)
- [x] add support for native runner (207)
- [x] pallet-evm: move to Frontier (Part III) (208)
- [x] Set block header `state_root` (209)
- [x] Restructure consensus crates (210)
- [x] Restructure rpc crates (211)
- [ ] Fix licenses (212) ***Skip***
- [x] Set receipt status info (219)
- [x] `status` field in transaction receipt (EIP658) (221)
- [x]  Add decoded revert reason to response message (224)
- [ ] Update README (225) ***Skip***
- [x] Require explictly evm 0.18.5 or newer (227)
- [x] Support for evm "estimate" flag for RPC estimation (230)
- [ ] Add documentation of overview, pallet-evm, pallet-ethereum(234) ***Skip***
- [x]  Accept None chain ID
- [x] Update to recent Substrate (236)
- [x] Adds modexp, bn128, blake2f, and ed25519 verify precompiles (239)
- [x] Separate precompiles to individual crates (242)
- [x] Add precompile support for Substrate dispatchables (246)
- [x] Add non-0 block gas limit. (244)
- [x] Expand Executed event (247)
- [x] Switch GasToWeight to GasWeightMapping (248)
- [x] WIP Modexp fixes (258)
- [x] Deserialize decimal inputs on BlockNumber (254)
- [x] Update peer_count return type (263)
- [x] Additional precompile fixes (261)
- [x] Support pending transactions on rpc (243)
- [x] AuxStore transactions one-to-many (193)
- [x] Set state root to intermediate Substrate block state root (255)
- [x] Use Get<H256> for state root instead of EthereumExt (264)
- [x] Bug fix + multi-address parameter support for `eth_getLogs` (250)
- [x] Abstract block gas limit (265)
- [ ] Refactoring ts-tests (272) ***Skip***
- [x] Improve binary search algorithm for gas estimation. (269)
- [x] Update substrate, evm and ethereum versions. (275)
- [x] Dynamic fee pallet for evm's FeeCalculator(278)
- [x] Fix topic wildcards bug (277)
- [x] Implement `EthFilterApi`(274)
- [x] New unified EVM runner (284)
- [ ] Add shell.nix for better NixOS support(281)  ***Skip***
- [x] Map genesis block hash in the auxstore(279)
- [x] Upgrade evm to 0.23 (287)
- [x] Handle system refcounts for pallet-evm managed contracts (288)
- [x] Make EVM pallet's storage items public. (289)
- [x] Introduce ConsensusLog::PostBlock and ConsensusLog::PreBlock (294)
- [x] Standalone backend database for Frontier (295)
- [x] Rpc small fixes (296)
- [x] Fix estimate_gas (297)
- [x] Move tx check (299)
- [x] Switch to `best` import notification for pubsub (305)
- [ ] Allow handling fee deductions done by EVM (307) ***Skip***
- [x] Mapping sync worker (309) 
- [x] Remove enabled flag (310) 
- [x] Separate PreLog and PostLog (311)
- [x] Add support for PreLog in pallet-ethereum (312)
- [x] Move template tasks into Frontier. (314)
- [x] Optional state overrides in RPC handler (199) 
- [ ] Update Substrate to v3.0 (313) 
- [x] The new rpc handle should returns the same data as the old one (316) 
- [ ] Move manual seal node template under a feature flag (317)  ***Skip***
- [x] Sha3FIPS standard precompiles and ECDSA public key recovery (304)
- [x] If the transaction fails, the log data should also be revert (302) 
- [x] Fix pre-log transaction processing (324)
- [x] Correctly handle re-org in mapping sync (326) 
- [x] Substrate 8b3e5bc (318)
- [x] Correct load transactions by hash (329)  
- [x] Decouple backend access from EthApi (331)
- [ ] Remove only() call in tests (335)  ***Skip***
- [x] Make block gas limit accessible in EVM contracts (332) 
- [x] Fix estimate gas when revert happened (338)
- [x] Fix `storage_at` override bug (339) 
- [x] Tx gas should never larger than block limit (346)
- [x] Switch to one-to-one block mapping in db (343) 
- [ ] Add missing Matrix link (350) ***Skip***
- [x] Schema override TODOs (345)
- [x] Remove useless param (351) 
- [x] mapping-sync: add support when ethereum pallet is introduced mid-way (341)

</details>

<details>
<summary>   2021.04.09 ~ 2021.06.30 </summary>

- [x] Fix pubsub transaction index (365)
- [x] Past events TODOs (364) 
- [x] Update substrate-bn to 0.6 (366)
- [ ] Add test for non-matching Filter. (367) ***Skip***
- [x] Proper Precompile Gas Consumption (337)
- [ ] docs: add instructions on how to use the dynamic fee pallet (371) ***Skip***
- [ ] Bump ssri from 6.0.1 to 6.0.2 in /docs (370)  ***Skip***
- [x] Pre-calculate Bloom (372)
- [x] Fix genesis block number generation (374)
- [x] Set transaction priority based on preliminary Weight (375)
- [x] min_gas_price check (379)
- [x] Optional net_peerCount response format (377)
- [x] Add curve25519 precompile (381)
- [ ] Upgrade EVM pallet to FRAMEv2 (380)
- [x] Update worker log level (383)
- [x] Update gas_price with dynamic-fee pallet (389)
- [x] Estimate_gas return issues (363) 
- [x] Use block's gas limit as default instead of U256::max_value() (393)
- [x] BN128 Bounds Checks (394)
- [x] Precompile output refactor (399)
- [x] Remove TargetMinGasPrice event (397)
- [x] Remove frontier offchain db on purge-chain subcommand (404)
- [x] Use skip_initialize_block for call and create (406)
- [x] Fix remaining release issues (415)
- [x] Add pallet_evm::Config::BlockHashMapping (409)
- [x] Update stack runner block_coinbase (411) 
- [x] Use TransactionPool notification stream in pusbub (412)
</details>

<details>
<summary>   2021.07.01 ~  2021.09.30</summary>

- [x] EVM Gas Benchmarks (413) 
- [x] Prioritize by gas price (419) 
- [x] Update stack runner block_gas_limit (410) 
- [x] Update roots in store_block(426)
- [x] Run CI with --locked flag (390)
- [x] DB worker syncing strategy (423)
- [x] Ensure that provided gas limit it never larger than current block's gas limit (428)
- [ ] Enable rustfmt (432)  ***Skip***
- [ ] Add Template Release Script (430) ***Skip***
- [x] Schema cache for log filtering (425)
- [x] Use gas limit instead of 1 billion for upper bound (436)
- [x] Update TargetMinGasPrice once in a block (435)
- [ ] Update Template use and utils (437) ***Skip***
- [ ] Final pallet release (443) ***Skip***
- [ ] Standardize git dependency and update Substrate master (444)
- [ ] Revert revert 380 (452)
- [ ] Update docs workflow nightly version (455)  ***Skip***
- [ ] Use reducible_balance instead free_balance (420)
- [ ] Update pallet-ethereum to new style (456)
- [ ] Prevent estimate_gas from OOGing more than twice (438)
- [ ] Remove unused pallet-evm hooks (405)
- [ ] Refactor Block struct (392)
- [ ] Fix bloom matching (457)
- [ ] Fix Event::Executed for transaction Call. (459)
- [ ] Create a security policy (461)  ***Skip***
- [x] Validate transaction cost (465)
</details>

<details>
<summary>   2021.10.01 ~  </summary>

 - [ ]  Remove unnecessary trait bound on Dispatch precompile (472)
 - [ ] Make libsecp256k1 a dev dependency (467)
 - [ ] template gen readme update (470)
 - [ ] Returns null receipt for non-canonical block transactions (474)
 - [ ] Refactor pending transactions (466)
 - [ ] Add LRU cache for eth block data and transactions statuses (479)
 - [ ] Signed Frontier-specific extrinsic (482)
 - [ ] Only use the pool when the transaction is not mapped (484)
 - [ ] Remove stray AuxStore trait bounds (487)
 - [ ] Prune unused imports (488)
 - [ ] pallet-ethereum must have feature runtime-benchmarks (489)
 - [ ] Bump num to 0.4 (490)
 - [ ] Make evm types public (496)
 - [ ] Estimate gas: impl geth algorithm for binary search (492)
 - [ ] Migrate dynamic fee pallet to attribute macros (491)
 - [ ] Move find_pre_log out of do_transact (493)
 - [ ] Fix security issue: transaction validity controls must be executed in STF (495)
 - [ ] Ensure no error is possible in apply_validated_transaction and fix correct_and_deposit_fee (497)
 - [ ] gas estimate: start close to the used gas only if it's lower than middle of the range (498)
 - [ ] fix estimate-gas (501)
 - [ ] All links moved to substrate.io (499)
 - [ ] estimateGas: if the first execution revert, it's not an exceeds allowance (503)
 - [ ] Patch substrate bug for refund on 0 ED chains (509)

</details>

**Comment by AsceticBear** [comment]
#363

**Comment by HackFisher** [comment]
- [ ] More Extensible Multiaddress Format https://github.com/paritytech/substrate/pull/7380

**Comment by AsceticBear** [comment]
https://github.com/darwinia-network/darwinia-common/pull/385

**Comment by AsceticBear** [comment]
I suggest keeping this issue open at present. We need to track the frontier upstream merge situation and update DVM in the future.

**Comment by AsceticBear** [comment]
https://github.com/darwinia-network/darwinia-common/pull/394

**Comment by AsceticBear** [comment]
#429

**Comment by AsceticBear** [comment]
#571

**Comment by AurevoirXavier** [comment]
Prefer to open a new one if needed.
