### ISSUE TITLE
Security Check: MPT Storage Leaf Node collision and bytes injection possiblities

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#375]
Because the mpt storage value and corresponding mpt proof are used by outside chain for storage member verification.

The verification is using the merkle leaf node(storage value for some prefix key) and corresponding merkle proof, and validate using the constraints/data of the leaf node value, so if their are other collision possibilities, or users can inject any bytes as leaf node by extrinsics without runtime checking, then the mpt verification could be affected.

Two cases need security checking:
  - Storage leaf node value collision, especially those collisions with verification node values such as customized event receipt in EthereumBacking module
  - Node value injection attack, e.g. some leaf node's value are `Vec<byte>`, and any user can bypass runtime checking and set its value.

TODO:

  - [ ] Move to [security wiki](https://github.com/darwinia-network/darwinia/wiki/Best-Practice-for-Darwinia-Security-Review) document

**Comment by AurevoirXavier** [comment]
Is able to recover the full path of MPT now.

**Comment by HackFisher** [comment]
Since the leaf value can be recovered using storage key and mpt proof, the storage key can not be conflicted, this could prevent the possibility of bytes injection.
![storage_key_aa](https://user-images.githubusercontent.com/1070122/101319669-50b51e00-389d-11eb-92b3-add5b32d2011.png)
![storage_key_bb](https://user-images.githubusercontent.com/1070122/101319680-53b00e80-389d-11eb-8f6f-17a218240c40.png)
![storage_key_cc](https://user-images.githubusercontent.com/1070122/101319690-56aaff00-389d-11eb-9b3c-3a116570a1ec.png)
