### ISSUE TITLE
Header Relay Proof for substrate-substrate bridge

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#408]
## General
Grandpa authorities are split into different rounds(aka. GrandpaSetId), round are auto increasing number. For each round there exists a `Header`, which includes a Grandpa Log Digest, defining following `ScheduledChange`, to indicate the scope start point and members of next Set, `start_point = header.height + delay`

```
/// A scheduled change of authority set.
#[cfg_attr(feature = "std", derive(Serialize))]
#[derive(Clone, Eq, PartialEq, Encode, Decode, RuntimeDebug)]
pub struct ScheduledChange<N> {
	/// The new authorities after the change, along with their respective weights.
	pub next_authorities: AuthorityList,
	/// The number of blocks to delay.
	pub delay: N,
}
```
Util the next `ScheduledChange` signaled by some Header, and end before the next round start.

The chain will use the grandpa justification to finalize specific header, the struct of Justification is like following:
```
#[derive(Clone, Encode, Decode, PartialEq, Eq, Debug)]
pub struct GrandpaJustification<Block: BlockT> {
   round: u64,
   pub(crate) commit: Commit<Block>,
   votes_ancestries: Vec<Block::Header>,
}
```

## Terminology

Hs(next_round = i) is the Header signal the ScheduleChange for the next round, its round id is i.
J(r = i, H) is the grandpa justification to finalize Header H using round i.

Note that the round and signatures in the Justification must match with related round's authorities, height of header to finalized must between the round's scope(Hs(next_round=r).height + delay(r) <= ? < Hs(next_round=r+1).height + delay(r+1))

## Example:

Source Chain:
```
Hs(nr=99)    ...   Hs(nr=100)    ...   Hs(nr=101)    ...   Header

Header.height >= Hs(nr=101).height + delay(101), and < Hs(nr=102).height + delay(102) (TODO: Question 1)
```

Target Chain:
```
Finalized Header is between Hs(nr=99) and Hs(nr=100)

Current_Finalized_Round = 99
```

What's the proof bridge relayer need to generate to finalize Header?

It should be
Proof
```
(
Header, J(r = 101, Header),
[
( Hs(nr=100), J(r=99, H where Hs(nr=100) <=H.height < Hs(nr=100) + delay(100)),
( Hs(nr=101), J(r=100, H where Hs(nr=101) <=H.height < Hs(nr=101) + delay(101))
]
)
```

## Question 1:
How the target chain verify that `Header.height >= Hs(nr=101).height + delay(101), and < Hs(nr=102).height + delay(102)` if we can not tell the max length of specific round. 

Which means, some relayer can use some justification generated by ancient outdated authority set (by bribing) to finalize some source chain header on target chain, because we can not tell how many Hs(nr=?) exists exactly before `Header`.

To resolve this, we can use some practical methods including max round length settings(usually 1 Era) and add assumption that ancient outdated authority set are not easy to be bribed. Update Hs with more frequency can also help reduce risk.

**Comment by AsceticBear** [comment]
> How the target chain verify that Header.height >= Hs(nr=101).height + delay(101), and < Hs(nr=102).height + delay(102) if we can not tell the max length of specific round.

The key point to finish this verification is to switch to the correct next Authority set list at Hs(nr=101).height + delay(101)  account to  Hs(nr=101) pre-pending changes set.

> because we can not tell how many Hs(nr=?) exists exactly before Header.

In current bridges-common, multiple scheduled changes on the same branch are not allowed when verifying block header in the target chain. Refer to this test for more detailed info https://github.com/paritytech/parity-bridges-common/blob/master/modules/substrate/src/fork_tests.rs#L169

**Comment by AsceticBear** [comment]
## Question 2:

Substrate light client in target chain will check block `requires_justification` flag when verifying finalize proof. The process requires all headers from last_finalized height to finalize proof height.

```rs
if let Some(ancestors) = headers_between(&self.storage, last_finalized, header.clone()) {
       let requires_justification = ancestors.iter().skip(1).find(|h| h.requires_justification);
       if requires_justification.is_some() {
		return Err(FinalizationError::PrematureJustification);
	}
}
```


```rs
fn headers_between<S, H>(
	storage: &S,
	ancestor: ImportedHeader<H>,
	child: ImportedHeader<H>,
) -> Option<Vec<ImportedHeader<H>>>
{
	while ancestor.hash() != current_header.hash() {
		// We've gotten to the same height and we're not related
		if ancestor.number() >= current_header.number() {
			return None;
		}

                // here
		let parent = storage.header_by_hash(*current_header.parent_hash());
		ancestors.push(current_header);
		current_header = match parent {
			Some(h) => h,
			None => return None,
		}
	}

	Some(ancestors)
}
```

**Comment by HackFisher** [comment]
Related: https://github.com/paritytech/parity-bridges-common/issues/263

**Comment by AsceticBear** [comment]
1. Header Relay Design With MMR

![header-relay](https://user-images.githubusercontent.com/11801722/104536968-01a89880-5654-11eb-9483-38aebd6bd833.jpg)


2. Message Relay Design With MMR

![message relay](https://user-images.githubusercontent.com/11801722/104536916-ee95c880-5653-11eb-8b75-8859e75e6c1b.jpg)

**Comment by HackFisher** [comment]
This is the summary and answer of the question in title, moving to wiki:

https://github.com/darwinia-network/darwinia/wiki/Darwinia-Bridge-Proposal
