### ISSUE TITLE
[Dvm] No Created event after dvm contract create 

### ISSUE THREAD

**Issue by freehere107** [darwinia-network/darwinia-common#409]
https://pangolin.subscan.io/extrinsic/187738-2

https://github.com/darwinia-network/darwinia-common/blob/4c52017ff005de837427e3941f5ddc60c6c4454f/frame/evm/src/lib.rs#L429

**Comment by AurevoirXavier** [comment]
Did you update the types?

**Comment by freehere107** [comment]
> Did you update the types?

yes

**Comment by AsceticBear** [comment]
When deploying a contract with web3 or remix, the ethereum tx finally executed in the EVM stack runner here https://github.com/darwinia-network/darwinia-common/blob/master/frame/evm/src/runner/stack.rs#L155. No event created.

To fix this issue, the best way is to expand the existing `Executed` event by add item `to`.

```rs
/// Ethereum pallet events.
	pub enum Event {
		/// An ethereum transaction was successfully executed. [from, transaction_hash, exitReason]
		Executed(H160, H256, ExitReason),
	}
```

here:

```rs
/// Ethereum pallet events.
	pub enum Event {
		/// An ethereum transaction was successfully executed. [from, to, transaction_hash, exitReason]
		Executed(H160, H160 H256, ExitReason),
	}
```

**Comment by AsceticBear** [comment]
https://github.com/paritytech/frontier/pull/247

**Comment by AurevoirXavier** [comment]
Need a PR to close this.
