### ISSUE TITLE
Dvm debug rpc

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#435]
Related: https://github.com/darwinia-network/darwinia-common/pull/428

**Comment by AurevoirXavier** [comment]
Seems this can be closed. @AsceticBear

**Comment by AsceticBear** [comment]
Not yet. The debug RPC is not implemented now.

**Comment by HackFisher** [comment]
Any update on this? @AsceticBear 

https://docs.moonbeam.network/builders/tools/debug-trace/

**Comment by AsceticBear** [comment]
After completing the fee market implementation, I will work on this issue.

**Comment by AsceticBear** [comment]
Something related:

1. https://github.com/paritytech/substrate/pull/7317
2. https://github.com/paritytech/substrate/issues/7035
3. https://github.com/paritytech/substrate/issues/9858
