### ISSUE TITLE
Msg need to include Nonce 

### ISSUE THREAD

**Issue by WoeOm** [darwinia-network/darwinia-common#444]
https://github.com/darwinia-network/darwinia-common/blob/4cf0a04f58b7148b7a84d6617eb8009139602825/frame/dvm/src/precompiles.rs#L116

Does msg need to include Nonce to ensure that it will not be attacked by replay?

**Comment by AsceticBear** [comment]
You are right! This is necessary to prevent replay attacks.

**Comment by AsceticBear** [comment]
Related with #319 , Close
