### ISSUE TITLE
Tx pending after calling payable contract function.

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-common#489]
https://github.com/evolutionlandorg/evo-deploy/blob/main/src/wrapper/WRING.sol#L34

```
合约地址 "TOKEN_ERC20_RING": "0x588abe3F7EE935137102C5e2B8042788935f4CB0",
```

Call `deposit()` from a 0 balance account.

**Comment by AsceticBear** [comment]
@hujw77  Can you test it on the latest pangolin network again? I think it should be solved already.

**Comment by hujw77** [comment]
I tested it manually on remix and it passed.
