### ISSUE TITLE
Wrong find_pre_log.is_error checking in internal func do_transact since this could be called by by pre_log in `on_initialize`

### ISSUE THREAD

**Issue by AsceticBear** [darwinia-network/darwinia-common#533]
More detailed info here: https://github.com/darwinia-network/darwinia-common/pull/498/files#r592909632

**Comment by AsceticBear** [comment]
https://github.com/paritytech/frontier/pull/324

**Comment by AurevoirXavier** [comment]
Can we close this now?

**Comment by AsceticBear** [comment]
Sorry for the delay. A patch has been drafted in the upstream repo just now. https://github.com/paritytech/frontier/pull/493
