### ISSUE TITLE
refact required for try_claim_deposits_with_punish API

### ISSUE THREAD

**Issue by songtianyi** [darwinia-network/darwinia-common#545]
https://github.com/darwinia-network/darwinia-common/blob/475093ec2e18da7f8e040c0908e6b1fcdf560c8c/frame/staking/src/lib.rs#L1622

The parameter `exprire_time` we pass in is calculated as follows:
```rust
INIT_TIMESTAMP + promise_month * MONTH_IN_MILLISECONDS,
```
When the controller account has multiple `deposit_items` which have the same sum for `expire_time`, the way we determine the deposit_item is not completely correct.
ex.
```
2 + 36 = 3 + 35

or more clearly

INIT_TIMESTAMP_1 + promise_month_1 * MONTH_IN_MILLISECONDS = INIT_TIMESTAMP_2 + promise_month_2 * MONTH_IN_MILLISECONDS
```
The right way is to pass the deposit_item index instead of expire_time.

**Comment by AurevoirXavier** [comment]
Almost impossible to happen on chain.

But good to make it better.

**Comment by HackFisher** [comment]
Staking will be removed/replaced in Darwinia 2.0
