### ISSUE TITLE
Update DVM gas_price

### ISSUE THREAD

**Issue by AsceticBear** [darwinia-network/darwinia-common#548]
![image](https://user-images.githubusercontent.com/11801722/111583939-1e01b680-87f8-11eb-9ea4-fbd8fac987fd.png)

**Comment by WoeOm** [comment]
https://github.com/MetaMask/metamask-extension/blob/1c573ef852e20789d3e2ff1233348a18c854fa4c/ui/app/ducks/gas/gas.duck.js#L115


if not ethereum mainnet , gasPrice fetching from RPC eth_gasPrice

**Comment by AsceticBear** [comment]
Now, gas_price = `1_000_000_000` is too low, Considering increase gas_price for Pangolin firstly, then Crab.

**Comment by AsceticBear** [comment]
We can update the gas_price using dynamic fee pallet now. close it.
