### ISSUE TITLE
Find why https://polkadot.js.org/ does not show balances?

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#57]
For latest 0.5.0 versions.

**Comment by AurevoirXavier** [comment]
> ![WechatIMG2373](https://user-images.githubusercontent.com/1070122/78753666-c84a4a80-79a8-11ea-9a25-d6e8c92216b0.jpeg)
> 
> The "Crab Session" have balances in apps.darwinia.network.

And this only happen when the account was bonded.

**Comment by AurevoirXavier** [comment]
Bring the `amount` and `reasons` fileds back, even they're useless.

```json
"BalanceLock": {
	"id": "LockIdentifier",
	"lock_for": "LockFor",
	"lock_reasons": "LockReasons",
	"amount": "Balance",
	"reasons": "Reasons"
},
```
