### ISSUE TITLE
When a failed transaction is called according by `eth_estimateGas`, the revert message should be returned.

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-common#572]
### branch 
`pangolin`

### Info
```shell
curl -fsS https://pangolin-rpc.darwinia.network -d '{"id":1,"jsonrpc":"2.0","method":"eth_estimateGas","param
s":[{"data":"0xc924a43b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
0000000000000005000000000000000000000000e9e0e23fb22865b20599ad4f2552d7f0824212d8","from":"0x0f14341A7f464320319025540E8Fe48Ad0fe5aec","
gas":"0x5b8d80","to":"0xef8ef3A1705f42e7FC1e06809940ec5942F5bB98"}]}' -H 'Content-Type: application/json'

{"jsonrpc":"2.0","result":"0x3b9aca00","id":1}
```

The call is failed, the revert message should be returned.

**Comment by AsceticBear** [comment]
https://github.com/paritytech/frontier/pull/338

**Comment by hujw77** [comment]
### reappear

**Comment by HackFisher** [comment]
@AsceticBear Did we do runtime and node upgrade to Pangolin before echo reproduce this?

**Comment by AsceticBear** [comment]
No，this issue reopened in the latest pangolin network(after reset Pangolin). The reason is that the `estimate_gas` interface should stop the estimate loop when `OutOfFund` happens in the Kton precompile. This issue only relates to the Kton precompile, so has no effect on DVM for crab.
