### ISSUE TITLE
KTON precompile bug

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#578]
Related #575 

https://github.com/darwinia-network/darwinia-common/blob/66ec3fb06b9ff3850fa3c909cc0150c3514808bc/frame/evm/precompile/contracts/kton/src/lib.rs#L79

There are bugs related to calculation for `transfer_value `.

**Comment by AsceticBear** [comment]
This will be fixed in the KTON precompile refactor pr later which i am working on.
