### ISSUE TITLE
Review: EthHeader's `PartialEq`

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#59]
I think this's wrong. @HackFisher 

```rust
impl PartialEq for EthHeader {
	fn eq(&self, c: &EthHeader) -> bool {
		if let (&Some(ref h1), &Some(ref h2)) = (&self.hash, &c.hash) {
			// Change to 
			// `if h1 != h2 { return false; }` 
			// would be more reasonable.
			if h1 == h2 {
				// `if h1 == h2` skip other fileds checking? 
				// Maybe ok, but better not.
				return true;
			}
		}

		// `if h1 != h2` keep checking other fileds? 
		// I don't think so.
		self.parent_hash == c.parent_hash
			&& self.timestamp == c.timestamp
			&& self.number == c.number
			&& self.author == c.author
			&& self.transactions_root == c.transactions_root
			&& self.uncles_hash == c.uncles_hash
			&& self.extra_data == c.extra_data
			&& self.state_root == c.state_root
			&& self.receipts_root == c.receipts_root
			&& self.log_bloom == c.log_bloom
			&& self.gas_used == c.gas_used
			&& self.gas_limit == c.gas_limit
			&& self.difficulty == c.difficulty
			&& self.seal == c.seal
	}
}
```

https://github.com/darwinia-network/darwinia-common/blob/master/primitives/eth-primitives/src/header.rs#L38

**Comment by HackFisher** [comment]
> I think this's wrong. @HackFisher
> 
> ```rust
> impl PartialEq for EthHeader {
> 	fn eq(&self, c: &EthHeader) -> bool {
> 		if let (&Some(ref h1), &Some(ref h2)) = (&self.hash, &c.hash) {
> 			// Change to 
> 			// `if h1 != h2 { return false; }` 
> 			// would be more reasonable.
> 			if h1 == h2 {
> 				// `if h1 == h2` skip other fileds checking? 
> 				// Maybe ok, but better not.
> 				return true;
> 			}
> 		}
> 
> 		// `if h1 != h2` keep checking other fileds? 
> 		// I don't think so.
> 		self.parent_hash == c.parent_hash
> 			&& self.timestamp == c.timestamp
> 			&& self.number == c.number
> 			&& self.author == c.author
> 			&& self.transactions_root == c.transactions_root
> 			&& self.uncles_hash == c.uncles_hash
> 			&& self.extra_data == c.extra_data
> 			&& self.state_root == c.state_root
> 			&& self.receipts_root == c.receipts_root
> 			&& self.log_bloom == c.log_bloom
> 			&& self.gas_used == c.gas_used
> 			&& self.gas_limit == c.gas_limit
> 			&& self.difficulty == c.difficulty
> 			&& self.seal == c.seal
> 	}
> }
> ```
> 
> https://github.com/darwinia-network/darwinia-common/blob/master/primitives/eth-primitives/src/header.rs#L38

Refer to the implementation in Parity Ethereum:

https://github.com/openethereum/openethereum/blob/master/ethcore/types/src/header.rs#L93
