### ISSUE TITLE
Refactor and migrate darwinia mmr pallet to use substrate mmr pallet

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#623]
1. Be consistent  with substrate, and eliminate the customization of pallet.
2. Substrate mmr pallet has advantages less on-chain storage. Its node collection only contains MMR peaks, the inner nodes (and leaves) are pruned and only stored in the Offchain DB (required by proof).

Take a look a recent Pangolin's vast [migration](https://github.com/darwinia-network/darwinia-common/pull/613/files#diff-d76e6add241f9f0be48db383dc3c10d6cd079d48703a6972e3ef9f3e64e29d80R811) (`move_prefix`)
https://github.com/paritytech/substrate/blob/4ff92f10058cfe1b379362673dd369e33a919e66/frame/merkle-mountain-range/src/lib.rs#L150

https://github.com/paritytech/substrate/blob/4ff92f10058cfe1b379362673dd369e33a919e66/frame/merkle-mountain-range/src/lib.rs#L225

3. Be careful with the data migration solution (runtime migration and Offchain DB data initialization), testing the consistency of the old/new node/root hashes.

4. Old mmr pallet uses old pallet name, new mmr pallet uses new pallet name, old pallet(and storage) can be deleted after migration/upgrade.

5. API changes for the bridger.

**Comment by AurevoirXavier** [comment]
https://github.com/paritytech/substrate/pull/9700

**Comment by AurevoirXavier** [comment]
Maybe in Darwinia 2.0.

**Comment by HackFisher** [comment]
Me will be removed in Darwinia 2.0
