### ISSUE TITLE
Optimize hashimoto by caching Light DAG in every epoch (30000)

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#64]
For every epoch, dag cache is same, does not require new each time.

TODO:

- [ ] Remove the disable test attr for hashimoto #66

**Comment by HackFisher** [comment]
Similar codes in open ethereum to ```verify_block_basic```

```
fn verify_block_unordered(pow: &Arc<EthashManager>, header: &Header) -> Result<(), Error> {
	let seal = EthashSeal::parse_seal(header.seal())?;

	let result = pow.compute_light(
		header.number(),
		&header.bare_hash().0,
		seal.nonce.to_low_u64_be()
	);
	let mix = H256(result.mix_hash);
	let difficulty = ethash::boundary_to_difficulty(&H256(result.value));
	trace!(target: "miner", "num: {num}, seed: {seed}, h: {h}, non: {non}, mix: {mix}, res: {res}",
	       num = header.number() as u64,
	       seed = H256(slow_hash_block_number(header.number() as u64)),
	       h = header.bare_hash(),
	       non = seal.nonce.to_low_u64_be(),
	       mix = H256(result.mix_hash),
	       res = H256(result.value));
	if mix != seal.mix_hash {
		return Err(From::from(BlockError::MismatchedH256SealElement(Mismatch {
			expected: mix,
			found: seal.mix_hash
		})));
	}
	if &difficulty < header.difficulty() {
		return Err(From::from(BlockError::InvalidProofOfWork(OutOfBounds {
			min: Some(*header.difficulty()),
			max: None,
			found: difficulty
		})));
	}
	Ok(())
}
```

**Comment by HackFisher** [comment]
We are going to use an alternative solution to resolve the optimization issue, refer the pull request #70 .

So it does not have quite value to continue with this optimization.

**Comment by HackFisher** [comment]
Would like to keep this re-open because it is a valuable question, and more benchmarks need to evaluate further, related #83 

Wondering that we didn't have the limitation that Waterloo and near have, because they must run the chain relay in smart contract, but we can run in runtime. This might means the 16MB dag cache /epoch solution still have its chance to live.

Re-open this due to above reasons.

**Comment by HackFisher** [comment]
BTW, advance features like ```runtime interface``` might bring more native resources/ability to runtime.

**Comment by AlexChien** [comment]
Not sure if it’s a good idea.  Wouldn’t that be too Ethereum specific?  What about other chains if they “require” something particular in runtime?
