### ISSUE TITLE
New MMRLeaf Spec

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-common#665]
Related to https://github.com/darwinia-network/darwinia-bridge-sol/pull/41

### MMR Leaf Spec
```
struct MMRLeaf {
  bytes32 parentHash;
  bytes32 messageCommitment;
}
```

### Inbound Message Spec 
```
struct Message {
    address target;
    uint64 nonce;
    bytes payload;
}
event MessageDispatched(uint64 nonce, bool result);
```

### Inbound Message Commitment Spec
```
keccak256(abi.encode(messages)) == commitment
```
Ref: https://github.com/Snowfork/snowbridge/blob/f28dc43a7267ab0e152cfd79e67244b0da0d34ed/parachain/pallets/basic-channel/src/outbound/mod.rs#L204

### Outbound Message Spec 
```
event Message(
    address source,
    uint64 nonce,
    bytes payload
);
```

**Comment by HackFisher** [comment]
Related: https://github.com/paritytech/grandpa-bridge-gadget/issues/221

**Comment by AurevoirXavier** [comment]
@hujw77 Spec needs to be updated.
