### ISSUE TITLE
MMR node list pruning algorithm

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#671]
```
/// MMR struct of the previous blocks, from first(genesis) to parent hash.
	#[pallet::storage]
	#[pallet::getter(fn mmr_node_list)]
	pub type MMRNodeList<T: Config> = StorageMap<_, Identity, u64, T::Hash, OptionQuery>;
```

`MMRNodeList` can be safely pruned to only keep peaks and move the pruned nodes to off-chain storage using [Off-Chain Indexing](https://substrate.dev/docs/en/knowledgebase/learn-substrate/off-chain-features)

The question will be what the best algorithm to pruning a dynamic increasing mmr node list (including merged nodes), and keep peaks(for easily add new leaf and calculate new mmr root instantly).

Ref:

https://github.com/nervosnetwork/merkle-mountain-range

**Comment by HackFisher** [comment]
Algorithm:

1. For specific mmr size `size_a`, we can safely pruning all none peak nodes in `MMR(size_a)`, since a none peak node is not possible to become a peak again after mmr grow.

2. When mmr grow to size `size_b`, there are some new leaves addes and some relevant new nodes accumulated on the mmr, we can easily calculate the peak positions of `MMR(size_a)` (existing set peak_a) and `MMR(size_B)` (set peak_b). We need to prune the nodes are exists in `peak_a` but not in peak_b, and prune the new generated nodes that are not in peak_b.

For a mmr with size of 5,000,000, the peaks is log2(mmr_size) which should be small(around 23). Step 2 should be fast and efficient.

3. After step 2, only peaks `size_b` is kept, and new leaves/nodes can still be safely added until next pruning size `size_c`, and continue repeat step 2.

**Comment by AurevoirXavier** [comment]
There are some empty implementations.

https://github.com/paritytech/polkadot/blob/master/runtime/kusama/src/lib.rs#L1647-L1670
