### ISSUE TITLE
use the same mapping-factory-contract for e2d and s2s bridge

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/darwinia-common#684]
- [ ] deploy a common contract and use the same code and address for two bridges
- [ ] move the parse code from frame/bridge/ethereum/issuing/contract to primitives/contract
- [ ] e2d use dispatch precompile contract, remove IssuingHandle

**Comment by HackFisher** [comment]
Related https://github.com/darwinia-network/darwinia-common/pull/731

@xiaoch05 Do we need to close this or update this?

**Comment by HackFisher** [comment]
@xiaoch05 Did this fixed in https://github.com/darwinia-network/darwinia-bridge-sol/pull/58 ?

**Comment by xiaoch05** [comment]
> @xiaoch05 Did this fixed in [darwinia-network/darwinia-bridge-sol#58](https://github.com/darwinia-network/darwinia-bridge-sol/pull/58) ?

Yes, we can close it now.

**Comment by xiaoch05** [comment]
fixed by https://github.com/darwinia-network/darwinia-common/pull/731 and https://github.com/darwinia-network/darwinia-bridge-sol/pull/58
