### ISSUE TITLE
Rust Docs Required

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#7]
Any PR is welcome. If you got confused feel free to contact the code owners.

**Comment by PedroJuan91** [comment]
where the `/primitives/relay` and `/frame/bridge//relayer-game/` documentation is written? I would like to be part of the documentation team. :)

**Comment by AurevoirXavier** [comment]
> where the `/primitives/relay` and `/frame/bridge/relayer-game/` documentation is written? I would like to be part of the documentation team. :)

In this PR, https://github.com/darwinia-network/darwinia-common/pull/268. Almost done.

**Comment by HackFisher** [comment]
@wuminzhe Would you please help promote and add these rust docs?

**Comment by AurevoirXavier** [comment]
It's time to clean up this.

Each pallet's code owners, please come to claim your tasks.

https://github.com/darwinia-network/darwinia-common/blob/master/docs/CODEOWNERS

**Comment by AsceticBear** [comment]
#807

**Comment by fewensa** [comment]
https://github.com/darwinia-network/bridger/pull/268

**Comment by AurevoirXavier** [comment]
- #807
- https://github.com/darwinia-network/bridger/pull/268
