### ISSUE TITLE
Record s2s transaction history in dvm

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/darwinia-common#704]
Right now, pallet cannot catch the error result of the dvm when call `do_transact`. The pallet should know the result and decide whether to revert the operation.
Now we use `do_call` instead. But this cannot be recorded in dvm receipt history. Some erc20 token transactions or some reverted transactions should be shown on explore.

**Comment by HackFisher** [comment]
Fixed in #713, use internal transact instead
