### ISSUE TITLE
The gas_limit of inner dvm transaction(system call)

### ISSUE THREAD

**Issue by xiaoch05** [darwinia-network/darwinia-common#706]
current, we use hard code 0x100000
it may cause outof gas problem

**Comment by HackFisher** [comment]
@AsceticBear Will this be fixed #713, and how the new approach resolve this?

**Comment by AsceticBear** [comment]
Yes, After 713 merged, the gas limit is `pub const INTERNAL_TX_GAS_LIMIT: u32 = 300_000_000;` I think this a big enough number for the gas limit.
