### ISSUE TITLE
CI `no_honesty_should_work ` Failed Unit Test

### ISSUE THREAD

**Issue by AurevoirXavier** [darwinia-network/darwinia-common#748]
```rust
---- tests::no_honesty_should_work stdout ----
thread 'tests::no_honesty_should_work' panicked at 'assertion failed: `(left == right)`
  left: `105`,
 right: `95`', frame/bridge/relayer-game/src/tests.rs:765:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by HackFisher** [comment]
@AsceticBear @AurevoirXavier  Why recent CI failed in this part? Giving this issue higher priority to fix it earlier.

**Comment by AurevoirXavier** [comment]
> @AsceticBear @AurevoirXavier Why recent CI failed in this part? Giving this issue higher priority to fix it earlier.

Looks like the github machine issues.

Can not reproduce locally. And re-run could fix this for CI.
