### ISSUE TITLE
Magic TransactionSignature in internal transaction

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#749]
https://github.com/darwinia-network/darwinia-common/pull/713/files#diff-400a8a292c291b6925055546f3901212cbea818b0c7b9806a1f7eb18290160a9R82

Why the parameters and chain id are hardcoded, does it still apply to testnet?

**Comment by AsceticBear** [comment]
> Why the parameters and chain id are hardcoded, does it still apply to testnet?

Would you like to provide more detailed info about this?

**Comment by HackFisher** [comment]
Following part in https://github.com/darwinia-network/darwinia-common/blob/00cc6ea6753bdb9d3750a9790a73ff6eafd36613/frame/dvm/rpc/runtime-api/src/lib.rs#L68 still looks magic to me:
```
signature: ethereum::TransactionSignature::new(
				// Reference https://github.com/ethereum/EIPs/issues/155
				//
				// But this transaction is sent by darwinia-issuing system from `0x0`
				// So ignore signature checking, simply set `chain_id` to `1`
				1 * 2 + 36,
				H256::from_slice(&[55u8; 32]),
				H256::from_slice(&[55u8; 32]),
			)
```

**Comment by AsceticBear** [comment]
The signature `new_internal_transaction` is just mock data that will not be used in later contexts. It would be much clear if there is a default implementation for TransactionSignature. check https://github.com/rust-blockchain/ethereum/pull/18

**Comment by AsceticBear** [comment]
Once https://github.com/paritytech/frontier/pull/481 is accepted, I think we can remove this black magic signature.

**Comment by AsceticBear** [comment]
This can be close after s2s-related pallets are removed.
