### ISSUE TITLE
Add types to Pangolin and Pangoro

### ISSUE THREAD

**Issue by HackFisher** [darwinia-network/darwinia-common#829]
For easier query last delivered message nonce

```
/// Delivered messages with their dispatch result.
#[derive(Clone, Default, Encode, Decode, RuntimeDebug, PartialEq, Eq)]
pub struct DeliveredMessages {
	/// Nonce of the first message that has been delivered (inclusive).
	pub begin: MessageNonce,
	/// Nonce of the last message that has been delivered (inclusive).
	pub end: MessageNonce,
	/// Dispatch result (`false`/`true`), returned by the message dispatcher for every
	/// message in the `[begin; end]` range. See `dispatch_result` field of the
	/// `bp_runtime::messages::MessageDispatchResult` structure for more information.
	pub dispatch_results: DispatchResultsBitVec,
}
```
https://github.com/darwinia-network/parity-bridges-common/blob/7be2b478b49bc8e87ddfe034076e9e80e2f126f6/primitives/messages/src/lib.rs#L208

**Comment by HackFisher** [comment]
![image](https://user-images.githubusercontent.com/1070122/133880616-0892b366-0d94-4ca2-9371-4f6b25a19855.png)


https://github.com/darwinia-network/parity-bridges-common/blob/main/deployments/types-wococo.json#L29-L83

**Comment by HackFisher** [comment]
For reference, but notice that the order here might be wrong:

**Comment by AurevoirXavier** [comment]
Better to make a pull request to Polkadot.

These are built-in types now.

**Comment by AurevoirXavier** [comment]
https://github.com/darwinia-network/darwinia.js/pull/24
