### ISSUE TITLE
Drop connection when subscribing to Event Logs

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-common#848]
## Script
https://crab-docs-edh5c847u-itering.vercel.app/builders/tools/pubsub#subscribing-to-event-logs-in-pangolin

## Error
```
Error: CONNECTION ERROR: The connection got closed with the close code `1006` and the following reason string `Connection dropped by remote peer.`
```

**Comment by wi1dcard** [comment]
Hey, it looks that the firewall in China reset the connection. As the RPC connection is built upon WebSocket, which is commonly used for people in China to bypass the firewall (especially through Cloudflare), somewhen the firewall started to cut off the suspicious connections.

Basically what you have to do is making sure that the conns are not exposed to the firewall, either using a proxy or VPN etc. 

If you're using this in the terminal with an HTTP proxy (not VPN), you probably have to 1) using a package like [tunnel](https://www.npmjs.com/package/tunnel) or [http-proxy-agent](https://www.npmjs.com/package/http-proxy-agent), and set it as the [`httpAgent` in web3.js](https://github.com/ChainSafe/web3.js/blob/5d027191c5cb7ffbcd44083528bdab19b4e14744/test/httpprovider.js#L31-L55). 2) Enable HTTP proxy set the `$http_proxy` and `$https_proxy` environment variable. Here's a [blog post](https://wi1dcard.dev/posts/redirecting-network-traffic-of-various-apps-on-macos-to-proxies/) that suggests some solutions on macOS.
