### ISSUE TITLE
Modify Ethereum offchain worker request and response

### ISSUE THREAD

**Issue by yanganto** [darwinia-network/darwinia-common#86]
Current request and reaponse follow Ethereum JSON RPC.
https://github.com/ethereum/wiki/wiki/JSON-RPC#eth_getblockbynumber

After discussion of requirement, we will not follow the Ethereum standard eventualy.  
Here is the protocol with fully discussed and ultilize the [SCALE Codec](https://substrate.dev/docs/en/conceptual/core/codec)

Relating issue: proof field #85 

There is a option to fallback the request with json format without codec and reuse most of the current code.

### Request:
POST  with `application/json` payload
```
{
  id: 1,
  jsonrpc: "2.0",
  method: "shadow_getEthHeaderWithProofByNumber",
  params: {"block_num": 1000, "transcation": false}
}
```

### Response:
all value in response encoded by [SCALE Codec](https://substrate.dev/docs/en/conceptual/core/codec)
```
{
  "id":1,
  "jsonrpc":"2.0",
  "result": {
    "eth_header":  "0xd4e5 ...scale_encoded_str",
    "proof": "0xd4e5...scale_encoded_str"
  }
}
```

### Request:
POST  with `application/json` payload
```
{
  id: 1,
  jsonrpc: "2.0",
  method: "shadow_getEthHeaderWithProofByNumber",
  params: {"block_num": 1000, "transcation": false, "options": {"format": "json"}}
}
```

### Response:
The value is followed our current test
https://github.com/darwinia-network/darwinia-common/blob/master/frame/bridge/eth/offchain/src/tests.rs#L14
```
{
  "id":1,
  "jsonrpc":"2.0",
  "result": {
    "eth_header": {
             the payload of eth_header is follow the current test
             https://github.com/darwinia-network/darwinia-common/blob/master/frame/bridge/eth/offchain/src/tests.rs#L14
          },
    "proof": [
               {
			"dag_nodes": ["0xabcd...", "0xebcd..."],
			"proof":["0xbbcde...", "0xabcde..."]
               },
		{
			"dag_nodes": ["0xabcd...", "0xebcd..."],
			"proof":["0xcccde...", "0xbbcde..."]
               }, ...
         ]
  }
}
```

**Comment by HackFisher** [comment]
The rpc service is provided by shadow service for offchain worker, how about using a related prefix
such as,
```
shadow_getEthHeaderWithProofByNumber
```

I prefer ```shadow_``` prefix rather than ```offchain_```, because in substrate rpc all, they use the module name as the prefix, so  ```offchain_``` might should be kept for offchain module itself.

```
{
  id: 1,
  jsonrpc: "2.0",
  method: "eth_getBlockWithProofByNumber",
  params: ["0x3e8", false]
}
```

**Comment by yanganto** [comment]
Okay, it will be `shadow_getEthHeaderWithProofByNumber`.

**Comment by clearloop** [comment]
I think we can use RESTful instead of JSON RPC

1. Most of JSON-RPC services are designed for network communication in the local network
2. RESTful API is easy to write, understand, and debug in the browser.
3. Another choice I like is `GraphQL`, but it's might need to write more code in `offchain-worker`

**Comment by yanganto** [comment]
Is the current spec acceptable?
The scale of EthHeader can refernce this commit
https://github.com/yanganto/darwinia-common/commit/7f65df2edcfa7b9b1746232bcb5879e2ff92f7a3#diff-60fd95e651d9296b453210dd13935942R783-R788

**Comment by yanganto** [comment]
@clearloop You still can propose RESTful API or any other format on this, if this is not aceptable.

**Comment by HackFisher** [comment]
I can imagine that, later on we could have task requirement for substrate offchain worker to query from chain db and POST to shadow service.

**Comment by HackFisher** [comment]
For options such as return format, we could define last parameter as the options, e.g. used for the result format codec/json etc.

In future, we may have more common options

```
{
  id: 1,
  jsonrpc: "2.0",
  method: "shadow_getEthHeaderWithProofByNumber",
  params: ["0x3e8", false, {"is_json": true}]
}
```

**Comment by yanganto** [comment]
modify b"\xd4\xe5" to "0xd4e5"

**Comment by yanganto** [comment]
> For options such as return format, we could define last parameter as the options, e.g. used for the result format codec/json etc.
> 
> In future, we may have more common options
> 
> ```
> {
>   id: 1,
>   jsonrpc: "2.0",
>   method: "shadow_getEthHeaderWithProofByNumber",
>   params: ["0x3e8", false, {"is_json": true}]
> }
> ```
> 
> If the last parameter is not passed, the service will use the default options.

Copy the solution from DingTalk, 
we will use these parameters, and options are not required field
` params: {"block_num": "0x3e8", "transcation": false, "options": {"format": "json"}}`

**Comment by yanganto** [comment]
Copy the conclusion from DingTalk, 
The `"options": {"format": "json"}` use the result already implemented.
https://github.com/darwinia-network/darwinia-common/blob/master/frame/bridge/eth/offchain/src/tests.rs#L14

**Comment by yanganto** [comment]
Comment from @clearloop 
block number in paramers should be `int`

ie,
params: {"block_num": "1000", "transcation": false, "options": {"format": "json"}}

**Comment by yanganto** [comment]
I am summarizing our conclusion to issue,  and this will be come into final determined if there is no further comment on this issue in 24 hrs.

**Comment by yanganto** [comment]
@clearloop, @HackFisher, @AurevoirXavier 
I update the issue info, if there is something unclear and ambiguous, please comment and help us finalized it. Thanks.

**Comment by yanganto** [comment]
update the link and description in the response part with option.

**Comment by yanganto** [comment]
The field `dag_node` should follow the [type.json](https://github.com/darwinia-network/darwinia-common/blob/master/bin/node-template/runtime/darwinia_types.json#L124), and should be `dag_nodes`, and its' value is `(H512, H512)`
ie, `"dag_node": "0xabcd..."` → `"dag_nodes": ["0xabcd...", "0xebcd..."]`

**Comment by yanganto** [comment]
Fix the typo `transcation` -> `transaction`  in params.

**Comment by HackFisher** [comment]
The spec doc moved to https://github.com/darwinia-network/darwinia/wiki/Darwinia-Offchain-Worker-Spec
