### ISSUE TITLE
Existence check before do `transfer_and_call` 

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/darwinia-common#921]
https://github.com/darwinia-network/darwinia-common/blob/fbfa84077396878fc7549f8d3465ef71be3197c9/frame/evm/precompile/contracts/transfer/src/kton.rs#L75

Due to the fact that the EVM considers a call to a non-existing contract to always succeed.
If `WKTON` is non-existing, the funds will be locked in the `wkton` address.
Here is the pseudo code.
```    
function isContract(address account) internal view returns (bool) {
        // This method relies on extcodesize, which returns 0 for contracts in
        // construction, since the code is only stored at the end of the
        // constructor execution.

        uint256 size;
        // solhint-disable-next-line no-inline-assembly
        assembly { size := extcodesize(account) }
        return size > 0;
    }
```
https://github.com/rust-blockchain/evm/blob/953f6cb16a07458d139e8dec5bafdc6cff4f6c4b/src/backend/memory.rs#L138

**Comment by AsceticBear** [comment]
There is a [wkton contract exist check](https://github.com/darwinia-network/darwinia-common/blob/master/frame/evm/precompile/contracts/transfer/src/kton.rs#L56-L59) before the call the wkton contract.  Can this can answer your question on this issue?

**Comment by hujw77** [comment]
> There is a [wkton contract exist check](https://github.com/darwinia-network/darwinia-common/blob/master/frame/evm/precompile/contracts/transfer/src/kton.rs#L56-L59) before the call the wkton contract. Can this can answer your question on this issue? @hujw77

LGTM
