### ISSUE TITLE
Remove `RialtoWeight` in some pallets config

### ISSUE THREAD

**Issue by AsceticBear** [darwinia-network/darwinia-common#953]
We should change it to something like `()` or our own benchmark result.

1. https://github.com/darwinia-network/darwinia-common/blob/master/node/runtime/pangolin/src/pallets/bridge_grandpa.rs#L28
2. https://github.com/darwinia-network/darwinia-common/blob/master/node/runtime/pangolin/src/pallets/bridge_messages.rs#L40
3. https://github.com/darwinia-network/darwinia-common/blob/master/node/runtime/pangoro/src/pallets/bridge_message.rs#L39
4. https://github.com/darwinia-network/darwinia-common/blob/master/node/runtime/pangoro/src/pallets/bridge_grandpa.rs#L27

**Comment by AurevoirXavier** [comment]
Will be done in #949
